In [4]:
import pandas as pd
import numpy as np
import re
import string
from pathlib import Path
import unicodedata
from time import perf_counter

In [5]:
BASE_DIR = Path("..")

TRAIN_DIR = BASE_DIR / "data" / "train"

S1_PATH = TRAIN_DIR / "train_source1.tsv"
S2_PATH = TRAIN_DIR / "train_source2.tsv"
S3_PATH = TRAIN_DIR / "train_source3.tsv"
GT_PATH = TRAIN_DIR / "train_ground_truth.tsv"

print(S1_PATH)
print(S2_PATH)
print(S3_PATH)
print(GT_PATH)

..\data\train\train_source1.tsv
..\data\train\train_source2.tsv
..\data\train\train_source3.tsv
..\data\train\train_ground_truth.tsv

In [6]:
s1_sample = pd.read_csv(
    S1_PATH,
    sep="\t",
    nrows=10
)

s2_sample = pd.read_csv(
    S2_PATH,
    sep="\t",
    nrows=10
)

s3_sample = pd.read_csv(
    S3_PATH,
    sep="\t",
    nrows=10
)

In [7]:
s1_sample

,entity_id,business_name,business_address,country
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US
2,S1-377745466,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US
3,S1-133037285,Christ Chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",US
4,S1-755362802,Prabhav Business Center,"797, Lake Town Block A, Kolkata, Howrah, West ...",India
5,S1-851869949,Custom Wealth Services LLC,"OH, Columbus, 5559 Orville Avenue",US
6,S1-785847572,Consulting Nyasa Nursing Private Limited,"2505, Tower 1, Oakwood, Runwal Greens, Mulund ...",India
7,S1-27541239,Nexus Anchor Rain,"1111 Church Street, Unit 2007, Nashville, TN",US
8,S1-629417405,Moore Bitwise Inc,"337 Oakland Avenue, Michigan City, IN",US
9,S1-22305073,Dermatology Green Medicine,"294 Meadowcreek Drive, Unit Unit 2, Village Of...",US

In [8]:
s2_sample

,entity_id,business_name,business_address,country
0,S2-166376419,राम मार्केटिंग प्राइवेट लिमिटेड,"KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi",India
1,S2-764573417,-- Holloway Peak Inc Seafood,"105 ELM ST, MORGANTON, NC",US
2,S2-639257739,आदित्य प्रॉपर्टीज एलएलपी,"G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh",India
3,S2-163963287,Summit Inc,"GREENSBORO, NC, 19 1/2 STARDUST TRAIL",US
4,S2-49942811,Delta Tetlecommunication Inc,"914 PIERPONT AVE, CLEVELAND, OH",US
5,S2-138046867,Lee and Lawson,"1702 Pine Avenue, CITY OF MENOMONIE, WI",US
6,S2-584977605,SHIVSHAKTI VIDYALAYA VIDYALAYA OVERSEAS CORPOR...,"H.NO 204 C ROAD HOSHIARPUR, PUNJAB, Punjab",India
7,S2-277444929,Shree Infracon Private Ltd,"63/2275/7, ALHIND TOWER, FIRST FLOOR, JAFFERKH...",India
8,S2-721031885,Chavira Platinum Chimera LLC,"282 SAXONY DRIVE, FTT MITCHELL, KY",US
9,S2-508602797,FOUNDATION EXCEL AGENCY PRIVATE LIMITED,"HN 753 E-1, BHARAT NAGAR, 104/1/1 ERANDWANE, M...",India

In [9]:
s3_sample

,entity_id,business_name,business_address,country
0,S3-202863386,wilfordhancock.com,"Mack Rd, Haltom City, Texas",US
1,S3-859268022,International South Consultants Private Ltd,NaN,India
2,S3-22467283,LLC Moncada Léarning Center,"5780 Fawn Ct, Fort Worth, Texas",US
3,S3-671162755,Moyna's Coffee,"1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio",US
4,S3-960981775,Pvt. EFS Print Ventures Ltd.,"Door No 183, 41St Cross, 22Nd Main 9Th Block J...",India
5,S3-578159284,LLC Hernandez Colonial Redwood,"2260- Housecreek Trail, Unit 407, Raleigh, Nor...",US
6,S3-121412624,Classic Equity Partners Group,"6885 Catalpa Bluff Ln, PO Box 5799, Dickinson,...",US
7,S3-249416830,Ectolumdrex dba X+ Madison Inc,"S03575 Cty Tk M, Town Of Buffalo, WI",US
8,S3-107644605,Animal Hanisch Hospirlg,"##8 Willow Oak Lane, Fl. 0, Saint Louis, Missouri",US
9,S3-160217003,Gomez Optimal,"343 Hempstead 161, Hope, Arkansas",US

In [10]:
print("S1 columns:")
print(s1_sample.columns.tolist())

print("\nS2 columns:")
print(s2_sample.columns.tolist())

print("\nS3 columns:")
print(s3_sample.columns.tolist())

S1 columns:
['entity_id', 'business_name', 'business_address', 'country']

S2 columns:
['entity_id', 'business_name', 'business_address', 'country']

S3 columns:
['entity_id', 'business_name', 'business_address', 'country']

In [11]:
s1_sample.iloc[0]

entity_id                                     S1-925783039
business_name                          Orelee's Barbershop
business_address    1795 Westchester Drive, High Point, NC
country                                                 US
Name: 0, dtype: object

In [12]:
SAMPLE_SIZE = 1000

s1_sample = pd.read_csv(
    S1_PATH,
    sep="\t",
    nrows=SAMPLE_SIZE
)

s2_sample = pd.read_csv(
    S2_PATH,
    sep="\t",
    nrows=SAMPLE_SIZE
)

s3_sample = pd.read_csv(
    S3_PATH,
    sep="\t",
    nrows=SAMPLE_SIZE
)

print("S1:", s1_sample.shape)
print("S2:", s2_sample.shape)
print("S3:", s3_sample.shape)

S1: (1000, 4)
S2: (1000, 4)
S3: (1000, 4)

In [13]:
for name, df in {
    "S1": s1_sample,
    "S2": s2_sample,
    "S3": s3_sample
}.items():

    print(f"\n{name}")
    print(df.isna().sum())

S1
entity_id           0
business_name       0
business_address    0
country             0
dtype: int64

S2
entity_id            0
business_name        0
business_address    35
country              0
dtype: int64

S3
entity_id            0
business_name        0
business_address    37
country              0
dtype: int64

In [14]:
def normalize_text(value):
    """
    Conservative normalization.

    - Handles missing values
    - Unicode normalization
    - Lowercase
    - Normalizes whitespace
    - Removes punctuation while preserving Unicode letters/numbers
    """
    if pd.isna(value):
        return ""

    value = str(value)

    # Normalize Unicode without deleting non-Latin scripts
    value = unicodedata.normalize("NFKC", value)

    # Lowercase
    value = value.lower()

    # Replace punctuation with spaces
    value = re.sub(r"[^\w\s]", " ", value, flags=re.UNICODE)

    # Normalize whitespace
    value = re.sub(r"\s+", " ", value).strip()

    return value

In [15]:
s1_sample["name_norm"] = s1_sample["business_name"].map(normalize_text)
s2_sample["name_norm"] = s2_sample["business_name"].map(normalize_text)
s3_sample["name_norm"] = s3_sample["business_name"].map(normalize_text)

In [16]:
s1_sample[["business_name", "name_norm"]].head(10)

,business_name,name_norm
0,Orelee's Barbershop,orelee s barbershop
1,Prime Money,prime money
2,B+ Retail Inc,b retail inc
3,Christ Chapel,christ chapel
4,Prabhav Business Center,prabhav business center
5,Custom Wealth Services LLC,custom wealth services llc
6,Consulting Nyasa Nursing Private Limited,consulting nyasa nursing private limited
7,Nexus Anchor Rain,nexus anchor rain
8,Moore Bitwise Inc,moore bitwise inc
9,Dermatology Green Medicine,dermatology green medicine

In [17]:
from collections import defaultdict

def build_name_index(df):
    index = defaultdict(list)

    for _, row in df.iterrows():
        name = row["name_norm"]

        if name:
            index[name].append(row["entity_id"])

    return index

In [18]:
s2_name_index = build_name_index(s2_sample)
s3_name_index = build_name_index(s3_sample)

print("S2 unique normalized names:", len(s2_name_index))
print("S3 unique normalized names:", len(s3_name_index))

S2 unique normalized names: 1000
S3 unique normalized names: 1000

In [19]:
def exact_name_candidates(s1_df, s2_index, s3_index):
    candidates = []

    for _, row in s1_df.iterrows():

        s1_id = row["entity_id"]
        name = row["name_norm"]

        if not name:
            continue

        # Search S2
        for candidate_id in s2_index.get(name, []):
            candidates.append({
                "s1_entity_id": s1_id,
                "candidate_entity_id": candidate_id,
                "source": "S2",
                "block_type": "exact_name"
            })

        # Search S3
        for candidate_id in s3_index.get(name, []):
            candidates.append({
                "s1_entity_id": s1_id,
                "candidate_entity_id": candidate_id,
                "source": "S3",
                "block_type": "exact_name"
            })

    return pd.DataFrame(candidates)

In [20]:
name_candidates = exact_name_candidates(
    s1_sample,
    s2_name_index,
    s3_name_index
)

name_candidates

   s1_entity_id candidate_entity_id source  block_type
0  S1-746273151        S3-538882911     S3  exact_name
1    S1-8092452        S3-551271002     S3  exact_name
2  S1-401074421        S3-303073926     S3  exact_name

In [21]:
pair = name_candidates.iloc[0]

s1_id = pair["s1_entity_id"]
candidate_id = pair["candidate_entity_id"]

print("S1 ID:", s1_id)
print("Candidate ID:", candidate_id)

S1 ID: S1-746273151
Candidate ID: S3-538882911

In [22]:
s1_match = s1_sample[
    s1_sample["entity_id"] == s1_id
]

s3_match = s3_sample[
    s3_sample["entity_id"] == candidate_id
]

display(
    s1_match[
        ["entity_id", "business_name", "business_address", "country", "name_norm"]
    ]
)

display(
    s3_match[
        ["entity_id", "business_name", "business_address", "country", "name_norm"]
    ]
)

,entity_id,business_name,business_address,country,name_norm
99,S1-746273151,Pediatric Dental Physicians Inc,"53 Laroche Lane, Hebron, ME",US,pediatric dental physicians inc

,entity_id,business_name,business_address,country,name_norm
646,S3-538882911,Pediatric Dental Physicians Inc.,NaN,US,pediatric dental physicians inc

In [23]:
print("Total candidate pairs:", len(name_candidates))

Total candidate pairs: 3

In [24]:
candidates_per_s1 = (
    name_candidates
    .groupby("s1_entity_id")
    .size()
)

print("S1 records with candidates:", len(candidates_per_s1))

if len(candidates_per_s1) > 0:
    print("Average:", candidates_per_s1.mean())
    print("Median:", candidates_per_s1.median())
    print("P95:", candidates_per_s1.quantile(0.95))
    print("P99:", candidates_per_s1.quantile(0.99))
    print("Maximum:", candidates_per_s1.max())

S1 records with candidates: 3
Average: 1.0
Median: 1.0
P95: 1.0
P99: 1.0
Maximum: 1

In [25]:
for _, pair in name_candidates.iterrows():
    print("=" * 70)
    print("S1:", pair["s1_entity_id"])
    print("Candidate:", pair["candidate_entity_id"])
    print("Source:", pair["source"])
    print("Block:", pair["block_type"])

    s1_row = s1_sample[
        s1_sample["entity_id"] == pair["s1_entity_id"]
    ]

    if pair["source"] == "S2":
        candidate_row = s2_sample[
            s2_sample["entity_id"] == pair["candidate_entity_id"]
        ]
    else:
        candidate_row = s3_sample[
            s3_sample["entity_id"] == pair["candidate_entity_id"]
        ]

    print("\nS1 record:")
    display(
        s1_row[
            ["entity_id", "business_name", "business_address", "country"]
        ]
    )

    print("\nCandidate record:")
    display(
        candidate_row[
            ["entity_id", "business_name", "business_address", "country"]
        ]
    )

======================================================================
S1: S1-746273151
Candidate: S3-538882911
Source: S3
Block: exact_name

S1 record:

,entity_id,business_name,business_address,country
99,S1-746273151,Pediatric Dental Physicians Inc,"53 Laroche Lane, Hebron, ME",US

Candidate record:

        entity_id                     business_name business_address country
646  S3-538882911  Pediatric Dental Physicians Inc.              NaN      US

======================================================================
S1: S1-8092452
Candidate: S3-551271002
Source: S3
Block: exact_name

S1 record:

      entity_id business_name                       business_address country
129  S1-8092452  Urban Nails!  1262 Grandstaff Avenue, Lancaster, OH      US

Candidate record:

        entity_id business_name                   business_address country
265  S3-551271002   Urban Nails  Wilson Pike, Brentwood, Tennessee      US

======================================================================
S1: S1-401074421
Candidate: S3-303073926
Source: S3
Block: exact_name

S1 record:

,entity_id,business_name,business_address,country
968,S1-401074421,Chau Minerals LLC,"1620 Belmont Street, Unit B, Washington, DC",US

Candidate record:

,entity_id,business_name,business_address,country
895,S3-303073926,Chau Minerals LLC,"1620 Belmont St, Washingtont Ownship, District...",US

In [26]:
def tokenize(value):
    if not value:
        return []

    return value.split()

In [27]:
s1_sample["name_tokens"] = s1_sample["name_norm"].map(tokenize)
s2_sample["name_tokens"] = s2_sample["name_norm"].map(tokenize)
s3_sample["name_tokens"] = s3_sample["name_norm"].map(tokenize)

s1_sample[["business_name", "name_norm", "name_tokens"]].head(10)

,business_name,name_norm,name_tokens
0,Orelee's Barbershop,orelee s barbershop,"[orelee, s, barbershop]"
1,Prime Money,prime money,"[prime, money]"
2,B+ Retail Inc,b retail inc,"[b, retail, inc]"
3,Christ Chapel,christ chapel,"[christ, chapel]"
4,Prabhav Business Center,prabhav business center,"[prabhav, business, center]"
5,Custom Wealth Services LLC,custom wealth services llc,"[custom, wealth, services, llc]"
6,Consulting Nyasa Nursing Private Limited,consulting nyasa nursing private limited,"[consulting, nyasa, nursing, private, limited]"
7,Nexus Anchor Rain,nexus anchor rain,"[nexus, anchor, rain]"
8,Moore Bitwise Inc,moore bitwise inc,"[moore, bitwise, inc]"
9,Dermatology Green Medicine,dermatology green medicine,"[dermatology, green, medicine]"

In [28]:
def build_token_index(df):
    index = defaultdict(set)

    for _, row in df.iterrows():
        entity_id = row["entity_id"]

        for token in row["name_tokens"]:
            if token:
                index[token].add(entity_id)

    return index

s2_name_token_index = build_token_index(s2_sample)
s3_name_token_index = build_token_index(s3_sample)

print("Unique S2 name tokens:", len(s2_name_token_index))
print("Unique S3 name tokens:", len(s3_name_token_index))

Unique S2 name tokens: 1810
Unique S3 name tokens: 1760

In [29]:
for token in list(s2_name_token_index.keys())[:20]:
    print(token, "→", list(s2_name_token_index[token])[:5])

र → ['S2-920169761', 'S2-735885703', 'S2-214924024', 'S2-314146870', 'S2-615967906']
म → ['S2-920169761', 'S2-735885703', 'S2-214924024', 'S2-314146870', 'S2-615967906']
क → ['S2-343318003', 'S2-920169761', 'S2-166376419', 'S2-707472784', 'S2-913216366']
ट → ['S2-920169761', 'S2-735885703', 'S2-214924024', 'S2-314146870', 'S2-615967906']
ग → ['S2-343318003', 'S2-389587679', 'S2-631299191', 'S2-166376419', 'S2-314146870']
प → ['S2-920169761', 'S2-735885703', 'S2-214924024', 'S2-314146870', 'S2-615967906']
इव → ['S2-920169761', 'S2-735885703', 'S2-214924024', 'S2-314146870', 'S2-615967906']
ल → ['S2-920169761', 'S2-735885703', 'S2-913216366', 'S2-214924024', 'S2-314146870']
ड → ['S2-920169761', 'S2-735885703', 'S2-214924024', 'S2-314146870', 'S2-615967906']
holloway → ['S2-764573417']
peak → ['S2-888440125', 'S2-623626120', 'S2-764573417', 'S2-836840386', 'S2-162336156']
inc → ['S2-736654053', 'S2-635511596', 'S2-472544795', 'S2-143614907', 'S2-871017791']
seafood → ['S2-764573417']
आद → ['S2-639257739']
त → ['S2-639257739', 'S2-546413297', 'S2-227749267']
य → ['S2-639257739']
पर → ['S2-639257739', 'S2-343318003']
ज → ['S2-343318003', 'S2-735885703', 'S2-273475397', 'S2-214924024', 'S2-314146870']
एलएलप → ['S2-639257739', 'S2-546413297', 'S2-707472784', 'S2-760590368']
summit → ['S2-305376778', 'S2-430379962', 'S2-163963287']

In [30]:
def name_token_candidates(s1_df, s2_index, s3_index):
    candidates = []

    for _, row in s1_df.iterrows():

        s1_id = row["entity_id"]
        tokens = row["name_tokens"]

        matched_s2 = set()
        matched_s3 = set()

        for token in tokens:
            matched_s2.update(s2_index.get(token, set()))
            matched_s3.update(s3_index.get(token, set()))

        for candidate_id in matched_s2:
            candidates.append({
                "s1_entity_id": s1_id,
                "candidate_entity_id": candidate_id,
                "source": "S2",
                "block_type": "name_token"
            })

        for candidate_id in matched_s3:
            candidates.append({
                "s1_entity_id": s1_id,
                "candidate_entity_id": candidate_id,
                "source": "S3",
                "block_type": "name_token"
            })

    return pd.DataFrame(candidates)

In [31]:
token_candidates_df = name_token_candidates(
    s1_sample,
    s2_name_token_index,
    s3_name_token_index
)

print("Total token-block candidates:", len(token_candidates_df))

token_candidates_df.head(20)

Total token-block candidates: 155171

    s1_entity_id candidate_entity_id source  block_type
0   S1-925783039        S2-281482759     S2  name_token
1   S1-925783039        S2-402804051     S2  name_token
2   S1-925783039        S2-832217093     S2  name_token
3   S1-925783039        S2-222674377     S2  name_token
4   S1-925783039         S2-34975790     S2  name_token
5   S1-925783039        S2-531458823     S2  name_token
6   S1-925783039        S2-930194769     S2  name_token
7   S1-925783039        S2-209019917     S2  name_token
8   S1-925783039        S2-769808418     S2  name_token
9   S1-925783039         S2-64137184     S2  name_token
10  S1-925783039         S2-30000261     S2  name_token
11  S1-925783039         S2-54521194     S2  name_token
12  S1-925783039        S2-655596796     S2  name_token
13  S1-925783039        S2-650540638     S2  name_token
14  S1-925783039        S2-373730786     S2  name_token
15  S1-925783039        S2-994612767     S2  name_token
16  S1-925783039        S2-554610011     S2  name_token
17  S1-925783039         S2-48939070     S2  name_token
18  S1-925783039         S2-41847464     S2  name_token
19  S1-925783039        S2-871017791     S2  name_token

In [32]:
if len(token_candidates_df) > 0:

    token_counts = (
        token_candidates_df
        .groupby("s1_entity_id")
        .size()
    )

    print("Total candidate pairs:", len(token_candidates_df))
    print("S1 records with candidates:", len(token_counts))
    print("Average:", token_counts.mean())
    print("Median:", token_counts.median())
    print("P95:", token_counts.quantile(0.95))
    print("P99:", token_counts.quantile(0.99))
    print("Maximum:", token_counts.max())

else:
    print("No token candidates found.")

Total candidate pairs: 155171
S1 records with candidates: 982
Average: 158.0152749490835
Median: 176.0
P95: 341.0
P99: 359.18999999999994
Maximum: 387

In [33]:
token_frequency_s2 = {
    token: len(entity_ids)
    for token, entity_ids in s2_name_token_index.items()
}

token_frequency_s3 = {
    token: len(entity_ids)
    for token, entity_ids in s3_name_token_index.items()
}

In [34]:
print("\nMost common S3 tokens:")

for token, count in sorted(
    token_frequency_s3.items(),
    key=lambda x: x[1],
    reverse=True
)[:30]:
    print(repr(token), "→", count)

Most common S3 tokens:
'limited' → 132
'private' → 126
'llc' → 93
'inc' → 85
'ltd' → 72
'pvt' → 44
'com' → 43
'center' → 34
's' → 33
'partners' → 33
'services' → 30
'india' → 29
'ल' → 26
'ट' → 25
'l' → 25
'group' → 24
'c' → 24
'ड' → 23
'र' → 23
'म' → 23
'holdings' → 22
'co' → 20
'and' → 20
'care' → 19
'corp' → 19
'a' → 19
'lp' → 19
'प' → 19
'इव' → 17
'corporation' → 14

In [35]:
NAME_STOPWORDS = {
    "inc", "llc", "ltd", "pvt", "co", "corp", "corporation",
    "limited", "group", "company", "the", "and", "of",
}


def build_token_index(df, token_col, stopwords=None, max_doc_freq=None):
    """
    Build an inverted index: token -> list of entity_ids containing that token.

    stopwords: tokens to skip entirely (too generic to be useful).
    max_doc_freq: if set, any token appearing in MORE than this many records
                  is dropped from the index after counting (protects against
                  tokens we didn't think to add to the stopword list).
    """
    stopwords = stopwords or set()
    index = defaultdict(list)

    for _, row in df.iterrows():
        entity_id = row["entity_id"]
        tokens = row[token_col]

        for token in tokens:
            if len(token) < 2 or token in stopwords:
                continue
            index[token].append(entity_id)

    if max_doc_freq is not None:
        index = {
            token: ids
            for token, ids in index.items()
            if len(ids) <= max_doc_freq
        }

    return index

In [36]:
s2_name_token_index = build_token_index(s2_sample, "name_tokens", stopwords=NAME_STOPWORDS)
s3_name_token_index = build_token_index(s3_sample, "name_tokens", stopwords=NAME_STOPWORDS)

print("S2 name-token index size:", len(s2_name_token_index))
print("S3 name-token index size:", len(s3_name_token_index))

token_doc_freq = sorted(
    ((token, len(ids)) for token, ids in s2_name_token_index.items()),
    key=lambda x: -x[1],
)
print("\nMost frequent S2 name tokens:")
for token, freq in token_doc_freq[:15]:
    print(f"  {token!r}: {freq}")

S2 name-token index size: 1639
S3 name-token index size: 1603

Most frequent S2 name tokens:
  'private': 121
  'com': 47
  'center': 38
  'partners': 35
  'इव': 32
  'services': 25
  'care': 25
  'india': 25
  'holdings': 18
  'llp': 17
  'associates': 14
  'global': 13
  'industries': 13
  'brothers': 10
  'service': 10

In [37]:
def token_block_candidates(s1_df, token_col, s2_index, s3_index, block_type):

    candidates = []

    for _, row in s1_df.iterrows():
        s1_id = row["entity_id"]
        tokens = row[token_col]

        if not tokens:
            continue

        matched_s2 = set()
        matched_s3 = set()

        for token in tokens:
            matched_s2.update(s2_index.get(token, []))
            matched_s3.update(s3_index.get(token, []))

        for candidate_id in matched_s2:
            candidates.append({
                "s1_entity_id": s1_id,
                "candidate_entity_id": candidate_id,
                "source": "S2",
                "block_type": block_type,
            })

        for candidate_id in matched_s3:
            candidates.append({
                "s1_entity_id": s1_id,
                "candidate_entity_id": candidate_id,
                "source": "S3",
                "block_type": block_type,
            })

    return pd.DataFrame(candidates)

In [38]:
name_token_candidates = token_block_candidates(
    s1_sample,
    "name_tokens",
    s2_name_token_index,
    s3_name_token_index,
    block_type="name_token",
)

print("Name-token candidate pairs:", len(name_token_candidates))
print("Exact-name candidate pairs (Strategy 1):", len(name_candidates))
name_token_candidates.head(10)

Name-token candidate pairs: 60110
Exact-name candidate pairs (Strategy 1): 3

   s1_entity_id candidate_entity_id source  block_type
0  S1-925783039        S2-415733261     S2  name_token
1  S1-773889195        S2-519912199     S2  name_token
2  S1-773889195        S3-325154278     S3  name_token
3  S1-773889195        S3-941511369     S3  name_token
4  S1-377745466        S2-325615566     S2  name_token
5  S1-377745466        S2-202057528     S2  name_token
6  S1-377745466        S2-477675434     S2  name_token
7  S1-377745466        S3-869462086     S3  name_token
8  S1-377745466        S3-657028395     S3  name_token
9  S1-133037285        S2-777835859     S2  name_token

In [39]:
def candidate_stats(candidates_df, label=""):

    if label:
        print(f"--- {label} ---")

    if len(candidates_df) == 0:
        print("No candidates generated.")
        return None

    per_s1 = candidates_df.groupby("s1_entity_id").size()

    print("S1 records with at least one candidate:", len(per_s1))
    print("Average candidates per S1:", per_s1.mean())
    print("Median candidates per S1:", per_s1.median())
    print("P95:", per_s1.quantile(0.95))
    print("P99:", per_s1.quantile(0.99))
    print("Max:", per_s1.max())

    return per_s1


_ = candidate_stats(name_token_candidates, label="Name-token block (sample)")

--- Name-token block (sample) ---
S1 records with at least one candidate: 888
Average candidates per S1: 67.69144144144144
Median candidates per S1: 13.0
P95: 256.0
P99: 280.0
Max: 301

In [40]:
def normalize_address(value):

    return normalize_text(value)


s1_sample["addr_norm"] = s1_sample["business_address"].map(normalize_address)
s2_sample["addr_norm"] = s2_sample["business_address"].map(normalize_address)
s3_sample["addr_norm"] = s3_sample["business_address"].map(normalize_address)

s1_sample[["business_address", "addr_norm"]].head(10)

,business_address,addr_norm
0,"1795 Westchester Drive, High Point, NC",1795 westchester drive high point nc
1,"17560 Ellis Road, Tahlequah, OK",17560 ellis road tahlequah ok
2,"1712 Montebello Avenue, Phoenix, AZ",1712 montebello avenue phoenix az
3,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",2100 cameron drive unit apartment g dundalk md
4,"797, Lake Town Block A, Kolkata, Howrah, West ...",797 lake town block a kolkata howrah west bengal
5,"OH, Columbus, 5559 Orville Avenue",oh columbus 5559 orville avenue
6,"2505, Tower 1, Oakwood, Runwal Greens, Mulund ...",2505 tower 1 oakwood runwal greens mulund gore...
7,"1111 Church Street, Unit 2007, Nashville, TN",1111 church street unit 2007 nashville tn
8,"337 Oakland Avenue, Michigan City, IN",337 oakland avenue michigan city in
9,"294 Meadowcreek Drive, Unit Unit 2, Village Of...",294 meadowcreek drive unit unit 2 village of p...

In [41]:
missing_addr_rows = s3_sample[s3_sample["business_address"].isna()]
missing_addr_rows[["entity_id", "business_name", "business_address", "addr_norm"]]

,entity_id,business_name,business_address,addr_norm
1,S3-859268022,International South Consultants Private Ltd,NaN,
52,S3-92001570,Davis Acquisition,NaN,
105,S3-299576808,"Morales, Godina & Pánkow Associates LLC",NaN,
110,S3-924073964,The Nancy Nancy Bunten Energy,NaN,
125,S3-588120445,Anand Agro Private Enterprises,NaN,
189,S3-32634960,Shyam Foundation Private Limited,NaN,
190,S3-509442398,New Delhi Techn0logies Private Limited,NaN,
231,S3-987949855,Southern பவர்,NaN,
251,S3-301461097,Al Macrktig Pvt Ltd,NaN,
302,S3-180062010,Beus Inc. Center,NaN,
346,S3-96513872,Carlynn Alumbaugh Quality-Hall Clinic,NaN,
351,S3-37104459,"Saia, Saia, L.L.C.",NaN,
382,S3-913436639,Heritage Motors L.L.C.,NaN,
402,S3-946323575,Desert Inc Institute,NaN,
451,S3-376509191,Northern Animal Hospital PLLC Foundation,NaN,
512,S3-28509014,"Nelia Moore, D.D.S., M.D., LLC",NaN,
539,S3-602996797,Saint Anthony Pediatric Dentistry Pioneer,NaN,
575,S3-875342922,Mendez Mrshall LLC,NaN,
628,S3-589621314,Vijay Projects Priavet Limited,NaN,
633,S3-894870818,R O Garcia (Partners),NaN,
646,S3-538882911,Pediatric Dental Physicians Inc.,NaN,
656,S3-572908938,TITAN TITAN LLC,NaN,
658,S3-868923476,Montelle Center,NaN,
722,S3-141506690,Dermatology Specialists Industries,NaN,
727,S3-514041989,"American Patriot Cohen, LLC",NaN,
740,S3-405814914,biex l.l.c.,NaN,
743,S3-454183630,Federal Pinnacle,NaN,
747,S3-439688939,Internal Group Services Enterprises,NaN,
801,S3-967973733,Ganganth Prefab Private,NaN,
808,S3-75691049,"Sullivan, Garner and Jones",NaN,
821,S3-718821474,Infra Hiteshi Livelihood Private Limited,NaN,
831,S3-699333493,J 5 K,NaN,
864,S3-448277175,Preferred Corporation LLC [Services],NaN,
914,S3-631045515,Pelaum Corp,NaN,
928,S3-67836226,Vargas Parmtiesr P.C.,NaN,
952,S3-552762137,integrated (india) india private limited,NaN,
963,S3-549886925,Helion Resorts (India) Private-Limited,NaN,

In [42]:
s1_sample["addr_tokens"] = s1_sample["addr_norm"].map(tokenize)
s2_sample["addr_tokens"] = s2_sample["addr_norm"].map(tokenize)
s3_sample["addr_tokens"] = s3_sample["addr_norm"].map(tokenize)

s1_sample[["business_address", "addr_norm", "addr_tokens"]].head(10)

,business_address,addr_norm,addr_tokens
0,"1795 Westchester Drive, High Point, NC",1795 westchester drive high point nc,"[1795, westchester, drive, high, point, nc]"
1,"17560 Ellis Road, Tahlequah, OK",17560 ellis road tahlequah ok,"[17560, ellis, road, tahlequah, ok]"
2,"1712 Montebello Avenue, Phoenix, AZ",1712 montebello avenue phoenix az,"[1712, montebello, avenue, phoenix, az]"
3,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",2100 cameron drive unit apartment g dundalk md,"[2100, cameron, drive, unit, apartment, g, dun..."
4,"797, Lake Town Block A, Kolkata, Howrah, West ...",797 lake town block a kolkata howrah west bengal,"[797, lake, town, block, a, kolkata, howrah, w..."
5,"OH, Columbus, 5559 Orville Avenue",oh columbus 5559 orville avenue,"[oh, columbus, 5559, orville, avenue]"
6,"2505, Tower 1, Oakwood, Runwal Greens, Mulund ...",2505 tower 1 oakwood runwal greens mulund gore...,"[2505, tower, 1, oakwood, runwal, greens, mulu..."
7,"1111 Church Street, Unit 2007, Nashville, TN",1111 church street unit 2007 nashville tn,"[1111, church, street, unit, 2007, nashville, tn]"
8,"337 Oakland Avenue, Michigan City, IN",337 oakland avenue michigan city in,"[337, oakland, avenue, michigan, city, in]"
9,"294 Meadowcreek Drive, Unit Unit 2, Village Of...",294 meadowcreek drive unit unit 2 village of p...,"[294, meadowcreek, drive, unit, unit, 2, villa..."

In [43]:
ADDRESS_STOPWORDS = {
    "street", "st", "road", "rd", "avenue", "ave", "lane", "ln",
    "drive", "dr", "near", "opp", "no", "nagar",
    "north", "south", "east", "west",
}

s2_addr_token_index = build_token_index(s2_sample, "addr_tokens", stopwords=ADDRESS_STOPWORDS)
s3_addr_token_index = build_token_index(s3_sample, "addr_tokens", stopwords=ADDRESS_STOPWORDS)

print("S2 address-token index size:", len(s2_addr_token_index))
print("S3 address-token index size:", len(s3_addr_token_index))

S2 address-token index size: 3147
S3 address-token index size: 2989

In [44]:
address_token_candidates = token_block_candidates(
    s1_sample,
    "addr_tokens",
    s2_addr_token_index,
    s3_addr_token_index,
    block_type="address_token",
)

print("Address-token candidate pairs:", len(address_token_candidates))
_ = candidate_stats(address_token_candidates, label="Address-token block (sample)")

Address-token candidate pairs: 85602
--- Address-token block (sample) ---
S1 records with at least one candidate: 1000
Average candidates per S1: 85.602
Median candidates per S1: 60.0
P95: 228.0
P99: 302.04999999999995
Max: 408

In [45]:
import re as _re  


def extract_leading_number(value):

    if not value:
        return None

    match = re.search(r"\d+", value)
    return match.group(0) if match else None


s1_sample["addr_number"] = s1_sample["addr_norm"].map(extract_leading_number)
s2_sample["addr_number"] = s2_sample["addr_norm"].map(extract_leading_number)
s3_sample["addr_number"] = s3_sample["addr_norm"].map(extract_leading_number)

s1_sample[["business_address", "addr_norm", "addr_number"]].head(10)

,business_address,addr_norm,addr_number
0,"1795 Westchester Drive, High Point, NC",1795 westchester drive high point nc,1795
1,"17560 Ellis Road, Tahlequah, OK",17560 ellis road tahlequah ok,17560
2,"1712 Montebello Avenue, Phoenix, AZ",1712 montebello avenue phoenix az,1712
3,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",2100 cameron drive unit apartment g dundalk md,2100
4,"797, Lake Town Block A, Kolkata, Howrah, West ...",797 lake town block a kolkata howrah west bengal,797
5,"OH, Columbus, 5559 Orville Avenue",oh columbus 5559 orville avenue,5559
6,"2505, Tower 1, Oakwood, Runwal Greens, Mulund ...",2505 tower 1 oakwood runwal greens mulund gore...,2505
7,"1111 Church Street, Unit 2007, Nashville, TN",1111 church street unit 2007 nashville tn,1111
8,"337 Oakland Avenue, Michigan City, IN",337 oakland avenue michigan city in,337
9,"294 Meadowcreek Drive, Unit Unit 2, Village Of...",294 meadowcreek drive unit unit 2 village of p...,294

In [46]:
def build_number_index(df, number_col, max_doc_freq=None):

    index = defaultdict(list)

    for _, row in df.iterrows():
        number = row[number_col]
        if number:
            index[number].append(row["entity_id"])

    if max_doc_freq is not None:
        index = {
            number: ids
            for number, ids in index.items()
            if len(ids) <= max_doc_freq
        }

    return index

MAX_NUMBER_DOC_FREQ = 5

s2_number_index = build_number_index(s2_sample, "addr_number", max_doc_freq=MAX_NUMBER_DOC_FREQ)
s3_number_index = build_number_index(s3_sample, "addr_number", max_doc_freq=MAX_NUMBER_DOC_FREQ)

print("S2 address-number index size:", len(s2_number_index))
print("S3 address-number index size:", len(s3_number_index))

S2 address-number index size: 631
S3 address-number index size: 609

In [47]:
def address_number_candidates(s1_df, s2_index, s3_index):
   
    candidates = []

    for _, row in s1_df.iterrows():
        s1_id = row["entity_id"]
        number = row["addr_number"]

        if not number:
            continue

        for candidate_id in s2_index.get(number, []):
            candidates.append({
                "s1_entity_id": s1_id,
                "candidate_entity_id": candidate_id,
                "source": "S2",
                "block_type": "address_number",
            })

        for candidate_id in s3_index.get(number, []):
            candidates.append({
                "s1_entity_id": s1_id,
                "candidate_entity_id": candidate_id,
                "source": "S3",
                "block_type": "address_number",
            })

    return pd.DataFrame(candidates)


number_candidates = address_number_candidates(s1_sample, s2_number_index, s3_number_index)

print("Address-number candidate pairs:", len(number_candidates))
_ = candidate_stats(number_candidates, label="Address-number block (sample)")

Address-number candidate pairs: 1074
--- Address-number block (sample) ---
S1 records with at least one candidate: 393
Average candidates per S1: 2.732824427480916
Median candidates per S1: 2.0
P95: 6.0
P99: 7.079999999999984
Max: 8

In [48]:
def combine_candidate_blocks(block_dfs):
   
    non_empty = [df for df in block_dfs if len(df) > 0]

    if not non_empty:
        return pd.DataFrame(
            columns=["s1_entity_id", "candidate_entity_id", "source", "retrieved_by"]
        )

    combined = pd.concat(non_empty, ignore_index=True)

    combined = (
        combined
        .groupby(["s1_entity_id", "candidate_entity_id", "source"])["block_type"]
        .agg(lambda block_types: sorted(set(block_types)))
        .reset_index()
        .rename(columns={"block_type": "retrieved_by"})
    )

    return combined


combined_candidates = combine_candidate_blocks([
    name_candidates,
    name_token_candidates,
    address_token_candidates,
    number_candidates,
])

total_raw = (
    len(name_candidates)
    + len(name_token_candidates)
    + len(address_token_candidates)
    + len(number_candidates)
)

print("Total candidate rows before dedup (sum across blocks):", total_raw)
print("Total unique candidate pairs after union + dedup:", len(combined_candidates))
combined_candidates.head(10)

Total candidate rows before dedup (sum across blocks): 146789
Total unique candidate pairs after union + dedup: 139156

   s1_entity_id candidate_entity_id source     retrieved_by
0  S1-100146655        S2-146516261     S2  [address_token]
1  S1-100146655        S2-147317655     S2  [address_token]
2  S1-100146655        S2-169701381     S2  [address_token]
3  S1-100146655        S2-172058052     S2  [address_token]
4  S1-100146655        S2-194307610     S2  [address_token]
5  S1-100146655        S2-200440168     S2  [address_token]
6  S1-100146655        S2-215156674     S2  [address_token]
7  S1-100146655        S2-259858270     S2  [address_token]
8  S1-100146655        S2-265287731     S2  [address_token]
9  S1-100146655        S2-278217555     S2  [address_token]

In [49]:
from collections import Counter

block_membership_counts = Counter()
for retrieved_by in combined_candidates["retrieved_by"]:
    for block_type in retrieved_by:
        block_membership_counts[block_type] += 1

print("How many combined candidate pairs each block contributed to:")
for block_type, count in block_membership_counts.most_common():
    print(f"  {block_type}: {count}")

multi_block_count = (combined_candidates["retrieved_by"].map(len) > 1).sum()
print(f"\nPairs retrieved by more than one block: {multi_block_count} / {len(combined_candidates)}")

combined_candidates[combined_candidates["retrieved_by"].map(len) > 1].head(10)

How many combined candidate pairs each block contributed to:
  address_token: 85602
  name_token: 60110
  address_number: 1074
  exact_name: 3

Pairs retrieved by more than one block: 7570 / 139156

     s1_entity_id candidate_entity_id source                     retrieved_by
228  S1-102971431        S2-155636061     S2      [address_token, name_token]
230  S1-102971431        S2-164651728     S2      [address_token, name_token]
234  S1-102971431        S2-178384635     S2      [address_token, name_token]
291  S1-102971431         S2-54720637     S2  [address_number, address_token]
294  S1-102971431        S2-556747559     S2      [address_token, name_token]
299  S1-102971431        S2-577969603     S2      [address_token, name_token]
309  S1-102971431        S2-652381513     S2      [address_token, name_token]
310  S1-102971431        S2-663049678     S2      [address_token, name_token]
320  S1-102971431        S2-708389947     S2      [address_token, name_token]
329  S1-102971431        S2-757169960     S2      [address_token, name_token]

In [50]:
_ = candidate_stats(combined_candidates, label="Combined blocks (sample, all 4 strategies)")

s1_with_candidates = set(combined_candidates["s1_entity_id"])
s1_without_candidates = set(s1_sample["entity_id"]) - s1_with_candidates

print(f"\nS1 records with at least one candidate: {len(s1_with_candidates)} / {len(s1_sample)}")
print(f"S1 records with NO candidates from any block: {len(s1_without_candidates)}")

--- Combined blocks (sample, all 4 strategies) ---
S1 records with at least one candidate: 1000
Average candidates per S1: 139.156
Median candidates per S1: 84.5
P95: 396.04999999999995
P99: 475.06999999999994
Max: 573

S1 records with at least one candidate: 1000 / 1000
S1 records with NO candidates from any block: 0

In [51]:
import json as _json

VALIDATION_DIR = BASE_DIR / "code" / "business_entity_resolution" / "src" / "validation_artifacts"

VAL_S1_IDS_PATH = VALIDATION_DIR / "val_s1_ids.txt"
VAL_GT_DICT_PATH = VALIDATION_DIR / "val_gt_dict.json"

print(VAL_S1_IDS_PATH)
print(VAL_GT_DICT_PATH)

..\code\business_entity_resolution\src\validation_artifacts\val_s1_ids.txt
..\code\business_entity_resolution\src\validation_artifacts\val_gt_dict.json

In [52]:
def load_val_s1_ids(path):
    with open(path, encoding="utf-8") as f:
        return [line.strip() for line in f if line.strip()]


def load_val_gt_dict(path):

    raw = path.read_text(encoding="utf-8", errors="replace")
    entries = re.findall(r'"(S1-[^"]+)":\s*\[(.*?)\]', raw, flags=re.DOTALL)

    val_gt = {}
    corrupted = []

    for s1_id, body in entries:
        raw_ids = re.findall(r'"([^"]*)"', body)
        cleaned = {i for i in raw_ids if i not in ("nan", "")}

        bad = [i for i in cleaned if not i.startswith(("S2-", "S3-"))]
        if bad:
            corrupted.append((s1_id, bad))

        val_gt[s1_id] = {i for i in cleaned if i.startswith(("S2-", "S3-"))}

    return val_gt, corrupted


val_s1_ids = load_val_s1_ids(VAL_S1_IDS_PATH)
val_gt_dict, corrupted_entries = load_val_gt_dict(VAL_GT_DICT_PATH)

print("Validation S1 IDs:", len(val_s1_ids))
print("Ground-truth entries loaded:", len(val_gt_dict))
print("Corrupted entries found:", len(corrupted_entries))

missing_from_dict = [s1_id for s1_id in val_s1_ids if s1_id not in val_gt_dict]
print(f"Validation IDs with NO ground-truth entry at all: {len(missing_from_dict)}")
if missing_from_dict:
    print("  (first 5):", missing_from_dict[:5])

Validation S1 IDs: 415947
Ground-truth entries loaded: 441289
Corrupted entries found: 1
Validation IDs with NO ground-truth entry at all: 72
  (first 5): ['S1-107932707', 'S1-12116720', 'S1-143649009', 'S1-159064592', 'S1-1622681']

In [53]:
def compute_candidate_recall(candidates_df, val_ids, val_gt):

    candidates_by_s1 = (
        candidates_df.groupby("s1_entity_id")["candidate_entity_id"]
        .apply(set)
        .to_dict()
    )

    per_entity_recall = []
    skipped = []

    for s1_id in val_ids:
        if s1_id not in val_gt:
            skipped.append(s1_id)
            continue

        true_matches = val_gt[s1_id]
        candidate_ids = candidates_by_s1.get(s1_id, set())

        if len(true_matches) == 0:
            per_entity_recall.append(1.0)
        else:
            found = len(true_matches & candidate_ids)
            per_entity_recall.append(found / len(true_matches))

    macro_recall = sum(per_entity_recall) / len(per_entity_recall) if per_entity_recall else 0.0

    return {
        "macro_candidate_recall": macro_recall,
        "n_evaluated": len(per_entity_recall),
        "n_skipped_no_ground_truth": len(skipped),
    }

print("compute_candidate_recall() is defined and ready for the full-scale run.")

compute_candidate_recall() is defined and ready for the full-scale run.

In [54]:
val_ids = val_s1_ids
val_gt = val_gt_dict

print("Validation S1 IDs:", len(val_ids))
print("Ground-truth entries:", len(val_gt))
print("Corrupted entries:", len(corrupted_entries))

Validation S1 IDs: 415947
Ground-truth entries: 441289
Corrupted entries: 1

In [55]:
print("First 5 validation S1 IDs:")
print(val_ids[:5])

print("\nFirst 5 ground-truth entries:")
for s1_id in list(val_gt.keys())[:5]:
    print(s1_id, "→", val_gt[s1_id])

First 5 validation S1 IDs:
['S1-100001512', 'S1-100002771', 'S1-100004023', 'S1-100005592', 'S1-100005874']

First 5 ground-truth entries:
S1-55344266 → {'S2-197070651', 'S3-384364074', 'S3-478195123', 'S2-249013014'}
S1-7293388 → {'S2-157073701', 'S2-442723188', 'S3-523120965', 'S2-7028416'}
S1-546142636 → {'S2-392804085', 'S2-487600131', 'S2-582477216', 'S3-200008747', 'S3-249331830', 'S3-729771680'}
S1-727602285 → {'S2-976870196', 'S2-947230367', 'S2-138660620', 'S2-23141904', 'S3-204655096'}
S1-840162906 → {'S3-799520471', 'S3-762681944', 'S3-800978181', 'S3-139858754', 'S2-129529678'}

In [56]:
VALIDATION_S1_IDS = set(val_ids)

s1_val = pd.read_csv(
    S1_PATH,
    sep="\t",
    usecols=[
        "entity_id",
        "business_name",
        "business_address",
        "country"
    ]
)

s1_val = s1_val[
    s1_val["entity_id"].isin(VALIDATION_S1_IDS)
].copy()

print("Validation S1 rows loaded:", len(s1_val))

Validation S1 rows loaded: 415946

In [57]:
s1_val["name_norm"] = (
    s1_val["business_name"]
    .map(normalize_text)
)

print(
    "Validation S1 records with non-empty names:",
    (s1_val["name_norm"] != "").sum()
)

Validation S1 records with non-empty names: 415946

In [58]:
def build_full_name_index(path, chunk_size=200_000):

    index = defaultdict(set)

    total_rows = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=["entity_id", "business_name"],
        chunksize=chunk_size
    ):

        total_rows += len(chunk)

        chunk["name_norm"] = (
            chunk["business_name"]
            .map(normalize_text)
        )

        chunk = chunk[chunk["name_norm"] != ""]

        for name, group in chunk.groupby("name_norm"):

            index[name].update(
                group["entity_id"].tolist()
            )

        print(
            f"Processed {total_rows:,} rows..."
        )

    return index

In [59]:
start = perf_counter()

s2_full_name_index = build_full_name_index(
    S2_PATH,
    chunk_size=200_000
)

elapsed = perf_counter() - start

print("\nS2 index built.")
print("Unique normalized names:", len(s2_full_name_index))
print(f"Time: {elapsed:.2f} seconds")

Processed 200,000 rows...
Processed 400,000 rows...
Processed 600,000 rows...
Processed 800,000 rows...
Processed 1,000,000 rows...
Processed 1,200,000 rows...
Processed 1,400,000 rows...
Processed 1,600,000 rows...
Processed 1,800,000 rows...
Processed 2,000,000 rows...
Processed 2,200,000 rows...
Processed 2,400,000 rows...
Processed 2,600,000 rows...
Processed 2,800,000 rows...
Processed 3,000,000 rows...
Processed 3,200,000 rows...
Processed 3,400,000 rows...
Processed 3,600,000 rows...
Processed 3,800,000 rows...
Processed 4,000,000 rows...
Processed 4,200,000 rows...
Processed 4,400,000 rows...
Processed 4,600,000 rows...
Processed 4,800,000 rows...
Processed 5,000,000 rows...
Processed 5,034,616 rows...

S2 index built.
Unique normalized names: 4025056
Time: 219.02 seconds

In [60]:
start = perf_counter()

s3_full_name_index = build_full_name_index(
    S3_PATH,
    chunk_size=200_000
)

elapsed = perf_counter() - start

print("\nS3 index built.")
print("Unique normalized names:", len(s3_full_name_index))
print(f"Time: {elapsed:.2f} seconds")

Processed 200,000 rows...
Processed 400,000 rows...
Processed 600,000 rows...
Processed 800,000 rows...
Processed 1,000,000 rows...
Processed 1,200,000 rows...
Processed 1,400,000 rows...
Processed 1,600,000 rows...
Processed 1,800,000 rows...
Processed 2,000,000 rows...
Processed 2,200,000 rows...
Processed 2,400,000 rows...
Processed 2,600,000 rows...
Processed 2,800,000 rows...
Processed 3,000,000 rows...
Processed 3,200,000 rows...
Processed 3,400,000 rows...
Processed 3,600,000 rows...
Processed 3,800,000 rows...
Processed 4,000,000 rows...
Processed 4,200,000 rows...
Processed 4,400,000 rows...
Processed 4,600,000 rows...
Processed 4,800,000 rows...
Processed 5,000,000 rows...
Processed 5,200,000 rows...
Processed 5,285,603 rows...

S3 index built.
Unique normalized names: 4280399
Time: 505.25 seconds

In [61]:
validation_name_candidates = exact_name_candidates(
    s1_val,
    s2_full_name_index,
    s3_full_name_index
)

print(
    "Total exact-name candidate pairs:",
    len(validation_name_candidates)
)

Total exact-name candidate pairs: 4124695

In [62]:
_ = candidate_stats(
    validation_name_candidates,
    label="Exact normalized-name block (validation)"
)

--- Exact normalized-name block (validation) ---
S1 records with at least one candidate: 295286
Average candidates per S1: 13.96847463137433
Median candidates per S1: 2.0
P95: 78.0
P99: 200.0
Max: 459

In [114]:
exact_name_recall = compute_candidate_recall(
    validation_name_candidates,
    val_ids,
    val_gt
)

print(exact_name_recall)

{'macro_candidate_recall': 0.2627617175664065, 'n_evaluated': 415875, 'n_skipped_no_ground_truth': 72}

Exact Normalized Name Blocking

Validation results:

- Candidate recall: 26.28%
- Total candidate pairs: 4,124,695
- Average candidates per S1: 13.97
- Median: 2
- P95: 78
- P99: 200
- Maximum: 459

In [67]:
from collections import Counter

def token_frequency_full(path, chunk_size=200_000):
    frequency = Counter()
    total_rows = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=["business_name"],
        chunksize=chunk_size
    ):
        total_rows += len(chunk)

        for name in chunk["business_name"]:
            normalized = normalize_text(name)

            if not normalized:
                continue

            tokens = set(normalized.split())
            frequency.update(tokens)

        print(f"Processed {total_rows:,} rows...")

    return frequency

In [68]:
start = perf_counter()

s2_token_frequency = token_frequency_full(S2_PATH)

print("\nS2 token frequency built.")
print("Unique tokens:", len(s2_token_frequency))
print(f"Time: {perf_counter() - start:.2f} seconds")

Processed 200,000 rows...
Processed 400,000 rows...
Processed 600,000 rows...
Processed 800,000 rows...
Processed 1,000,000 rows...
Processed 1,200,000 rows...
Processed 1,400,000 rows...
Processed 1,600,000 rows...
Processed 1,800,000 rows...
Processed 2,000,000 rows...
Processed 2,200,000 rows...
Processed 2,400,000 rows...
Processed 2,600,000 rows...
Processed 2,800,000 rows...
Processed 3,000,000 rows...
Processed 3,200,000 rows...
Processed 3,400,000 rows...
Processed 3,600,000 rows...
Processed 3,800,000 rows...
Processed 4,000,000 rows...
Processed 4,200,000 rows...
Processed 4,400,000 rows...
Processed 4,600,000 rows...
Processed 4,800,000 rows...
Processed 5,000,000 rows...
Processed 5,034,616 rows...

S2 token frequency built.
Unique tokens: 810514
Time: 49.67 seconds

In [69]:
start = perf_counter()

s3_token_frequency = token_frequency_full(S3_PATH)

print("\nS3 token frequency built.")
print("Unique tokens:", len(s3_token_frequency))
print(f"Time: {perf_counter() - start:.2f} seconds")

Processed 200,000 rows...
Processed 400,000 rows...
Processed 600,000 rows...
Processed 800,000 rows...
Processed 1,000,000 rows...
Processed 1,200,000 rows...
Processed 1,400,000 rows...
Processed 1,600,000 rows...
Processed 1,800,000 rows...
Processed 2,000,000 rows...
Processed 2,200,000 rows...
Processed 2,400,000 rows...
Processed 2,600,000 rows...
Processed 2,800,000 rows...
Processed 3,000,000 rows...
Processed 3,200,000 rows...
Processed 3,400,000 rows...
Processed 3,600,000 rows...
Processed 3,800,000 rows...
Processed 4,000,000 rows...
Processed 4,200,000 rows...
Processed 4,400,000 rows...
Processed 4,600,000 rows...
Processed 4,800,000 rows...
Processed 5,000,000 rows...
Processed 5,200,000 rows...
Processed 5,285,603 rows...

S3 token frequency built.
Unique tokens: 863014
Time: 49.40 seconds

In [70]:
print("TOP S2 TOKENS")
for token, count in s2_token_frequency.most_common(30):
    print(repr(token), "→", count)

print("\nTOP S3 TOKENS")
for token, count in s3_token_frequency.most_common(30):
    print(repr(token), "→", count)

TOP S2 TOKENS
'limited' → 528795
'llc' → 528303
'private' → 528131
'inc' → 400229
'ltd' → 398464
'ल' → 237102
'ट' → 232862
'र' → 226825
'ड' → 208515
'प' → 206868
'म' → 206488
'com' → 201464
'center' → 193696
'pvt' → 189270
'स' → 160325
'इव' → 157955
'partners' → 152694
'services' → 145239
'corp' → 141773
'co' → 139561
'group' → 139390
's' → 138303
'and' → 118201
'c' → 113281
'india' → 110684
'क' → 105891
'holdings' → 97019
'l' → 93771
'care' → 88788
'of' → 87992

TOP S3 TOKENS
'limited' → 673480
'private' → 639861
'llc' → 571362
'ltd' → 427781
'inc' → 419917
'center' → 220809
'pvt' → 220353
'com' → 211116
'services' → 166621
'partners' → 161955
's' → 147647
'group' → 144614
'co' → 143838
'corp' → 140236
'ल' → 134117
'ट' → 132429
'र' → 128844
'and' → 122220
'ड' → 117653
'प' → 116694
'म' → 116370
'c' → 113132
'india' → 112959
'holdings' → 99024
'care' → 95821
'of' → 90980
'स' → 90553
'l' → 89809
'इव' → 88517
'a' → 79896

In [71]:
s2_token_frequency
s3_token_frequency

Counter({'limited': 673480,
         'private': 639861,
         'llc': 571362,
         'ltd': 427781,
         'inc': 419917,
         'center': 220809,
         'pvt': 220353,
         'com': 211116,
         'services': 166621,
         'partners': 161955,
         's': 147647,
         'group': 144614,
         'co': 143838,
         'corp': 140236,
         'ल': 134117,
         'ट': 132429,
         'र': 128844,
         'and': 122220,
         'ड': 117653,
         'प': 116694,
         'म': 116370,
         'c': 113132,
         'india': 112959,
         'holdings': 99024,
         'care': 95821,
         'of': 90980,
         'स': 90553,
         'l': 89809,
         'इव': 88517,
         'a': 79896,
         'llp': 77190,
         'associates': 76679,
         'd': 64840,
         'service': 63953,
         'क': 59798,
         'p': 58730,
         'corporation': 58097,
         'enterprises': 56858,
         'the': 54457,
         'health': 53452,
         'industries': 53419,
         'trading': 51791,
         'ventures': 49367,
         'm': 48771,
         'clinic': 48097,
         'solutions': 46367,
         'lp': 45763,
         'global': 42268,
         'pc': 40325,
         'ज': 38770,
         'public': 37634,
         'brothers': 36259,
         'technologies': 35659,
         'pediatric': 35021,
         'exports': 33711,
         'medicine': 33121,
         'न': 32659,
         'international': 32004,
         'ग': 31951,
         'company': 31866,
         'dba': 31629,
         'k': 31537,
         'formerly': 30057,
         'फ': 29739,
         'mr': 29514,
         'sri': 29388,
         'dr': 29334,
         'smt': 29293,
         'shri': 29207,
         'foundation': 28906,
         'as': 28845,
         'dental': 27422,
         'य': 26880,
         'b': 26807,
         'pllc': 26549,
         'business': 25677,
         'trust': 25370,
         'family': 25330,
         'blue': 24752,
         'summit': 24697,
         'valley': 24697,
         'व': 24645,
         'consultants': 24536,
         'highland': 24376,
         'green': 24185,
         'इ': 24017,
         'metro': 23578,
         'north': 23575,
         'overseas': 23546,
         'coastal': 23442,
         'infratech': 23419,
         'harbor': 23259,
         'east': 23245,
         'south': 22979,
         'golden': 22919,
         'capital': 22669,
         'traders': 22311,
         'silver': 22296,
         'new': 22119,
         'technology': 21939,
         'management': 21817,
         'engineering': 21800,
         'incorporated': 21769,
         'bright': 21690,
         'specialists': 21365,
         'first': 21364,
         'systems': 21145,
         'creative': 21062,
         'ట': 20986,
         'marketing': 20934,
         'vision': 20817,
         'institute': 20815,
         'f': 20715,
         'ब': 20248,
         'united': 20222,
         'tech': 20021,
         'products': 20018,
         'ಟ': 19969,
         'school': 19684,
         'premier': 19592,
         'dynamic': 19562,
         'sons': 19487,
         'డ': 19476,
         'ల': 19414,
         'మ': 19395,
         'all': 19336,
         'ర': 19322,
         'star': 19321,
         'límited': 19275,
         'physicians': 19203,
         'west': 19131,
         'apex': 19055,
         'great': 18998,
         'smart': 18820,
         'prime': 18654,
         'ಲ': 18627,
         'ಮ': 18564,
         'ಡ': 18556,
         'royal': 18543,
         'ட': 18401,
         'ರ': 18300,
         'foods': 18275,
         'digital': 18243,
         'best': 18194,
         'ప': 18053,
         'innovative': 17963,
         'ace': 17753,
         'regional': 17709,
         'pioneer': 17705,
         'society': 17659,
         'developers': 17506,
         'energy': 17410,
         'media': 17399,
         'delhi': 17389,
         'ಪ': 17290,
         'consultancy': 17245,
         'construction': 17237,
         'వ': 17217,
         'properties': 17118,
         'software': 17108,
         'city': 17034,
         'modern': 17007,
         'classic': 16899,
         'prívate': 16765,
         'supreme': 16711,
         'श': 16707,
         'ம': 16704,
         't': 16673,
         'it': 16553,
         'ர': 16533,
         'www': 16526,
         'ல': 16455,
         'ವ': 16434,
         'यर': 16424,
         'infrastructure': 16396,
         'id': 16313,
         'ট': 16285,
         'ப': 16258,
         'fresh': 16178,
         'heritage': 16053,
         'finance': 15930,
         'agro': 15928,
         'smith': 15807,
         'র': 15696,
         'pacific': 15576,
         'therapy': 15477,
         'ল': 15466,
         'ह': 15452,
         'ড': 15391,
         'allied': 15331,
         'લ': 15327,
         'hospitality': 15256,
         'ટ': 15149,
         'ম': 15130,
         'federal': 15112,
         'national': 15093,
         'investments': 15029,
         'atlantic': 15027,
         'consulting': 14950,
         'mountain': 14944,
         'ર': 14922,
         'logistics': 14837,
         'state': 14818,
         'medical': 14758,
         'cardiology': 14710,
         'o': 14706,
         'வ': 14660,
         'producer': 14649,
         'infra': 14616,
         'american': 14598,
         'interstate': 14597,
         'cascade': 14569,
         'liberty': 14565,
         'స': 14550,
         'empire': 14451,
         'continental': 14407,
         'healthcare': 14380,
         'shree': 14373,
         'union': 14354,
         'integrated': 14343,
         'labs': 14306,
         'physical': 14272,
         'metropolitan': 14235,
         'ridge': 14233,
         'eye': 14190,
         'rocky': 14037,
         'tri': 13946,
         'advanced': 13792,
         'ínc': 13767,
         'delta': 13678,
         'bay': 13665,
         'precision': 13632,
         'works': 13625,
         'chiropractic': 13611,
         'dds': 13611,
         'patriot': 13584,
         'horizon': 13573,
         'one': 13567,
         'uptown': 13549,
         'strategic': 13532,
         'downtown': 13528,
         'builders': 13464,
         'প': 13422,
         'sterling': 13370,
         'pinnacle': 13369,
         'ડ': 13363,
         'midwest': 13353,
         'પ': 13313,
         'superior': 13295,
         'safe': 13259,
         'prairie': 13215,
         'મ': 13183,
         'express': 13171,
         'ಸ': 13168,
         'investment': 13091,
         'projects': 13069,
         'reliable': 13067,
         'piedmont': 13040,
         'frontier': 13030,
         'colonial': 12978,
         'desert': 12975,
         'alliance': 12974,
         'keystone': 12866,
         'total': 12827,
         'quality': 12825,
         'heartland': 12819,
         'gulf': 12812,
         'vanguard': 12762,
         'unified': 12757,
         'clean': 12737,
         'constructions': 12724,
         'elite': 12667,
         'johnson': 12537,
         'church': 12449,
         'ইভ': 12448,
         'value': 12443,
         'anchor': 12442,
         'platinum': 12414,
         'choice': 12394,
         'select': 12330,
         'better': 12289,
         'preferred': 12281,
         'association': 12275,
         'direct': 12275,
         'mumbai': 12271,
         'cornerstone': 12164,
         'diamond': 12143,
         'power': 12127,
         'surgical': 12110,
         'academy': 12066,
         'beacon': 11980,
         'grand': 11957,
         'ear': 11956,
         'peak': 11939,
         'auto': 11915,
         'primary': 11913,
         'crystal': 11896,
         'legacy': 11866,
         'signature': 11808,
         'rapid': 11785,
         'advisors': 11731,
         'custom': 11707,
         'central': 11701,
         'foot': 11693,
         'oncology': 11658,
         'certified': 11609,
         'big': 11573,
         'urban': 11555,
         'complete': 11544,
         'clear': 11508,
         'secure': 11498,
         'network': 11473,
         'w': 11391,
         'dermatology': 11386,
         'optimal': 11376,
         'trusted': 11352,
         'behavioral': 11246,
         'womens': 11229,
         'urgent': 11134,
         'food': 11059,
         'internal': 11033,
         'orthopedic': 10976,
         'throat': 10972,
         'white': 10915,
         'eastern': 10875,
         'estate': 10860,
         'સ': 10849,
         'red': 10842,
         'nose': 10834,
         'सल': 10810,
         'southern': 10761,
         'इन': 10693,
         'urology': 10683,
         'aka': 10681,
         'home': 10626,
         'infotech': 10571,
         'local': 10553,
         'dentistry': 10451,
         'impex': 10430,
         'doing': 10391,
         'ankle': 10381,
         'ஸ': 10284,
         'williams': 10262,
         'त': 10250,
         'life': 10113,
         'ઇવ': 10073,
         'hospital': 9759,
         'realty': 9715,
         'रक': 9698,
         'റ': 9625,
         'education': 9611,
         'greater': 9609,
         'riverside': 9560,
         'westgate': 9536,
         'lakeside': 9523,
         'northside': 9509,
         'southside': 9451,
         'midtown': 9417,
         'jones': 9380,
         'brown': 9340,
         'eastgate': 9314,
         'മ': 9307,
         'fund': 9267,
         'ല': 9245,
         'sai': 9083,
         'റഡ': 8973,
         'टम': 8910,
         'environmental': 8908,
         'ര': 8885,
         'hotel': 8880,
         'bangalore': 8867,
         'real': 8866,
         'security': 8799,
         'worldwide': 8793,
         'एलएलप': 8614,
         'चर': 8544,
         'പ': 8441,
         'welfare': 8441,
         'electronics': 8435,
         'স': 8288,
         'ministries': 8255,
         'community': 8226,
         'council': 8150,
         'laboratories': 8149,
         'networks': 8115,
         'memorial': 8102,
         'fellowship': 8062,
         'studios': 7988,
         'federation': 7855,
         'super': 7807,
         'க': 7786,
         'വറ': 7784,
         'cleaning': 7700,
         'studio': 7638,
         'innovations': 7631,
         'universal': 7551,
         'sun': 7521,
         'known': 7508,
         'née': 7503,
         'fka': 7492,
         'project': 7468,
         'college': 7467,
         'jai': 7438,
         'office': 7354,
         'cure': 7335,
         'maa': 7314,
         'black': 7235,
         'garcia': 7221,
         'miller': 7184,
         'financial': 7173,
         'om': 7152,
         'bakery': 7112,
         'future': 7097,
         'క': 7097,
         'animal': 7094,
         'research': 7082,
         'development': 7052,
         'data': 6993,
         'davis': 6991,
         'gold': 6976,
         'centre': 6961,
         'law': 6947,
         'high': 6935,
         'v': 6924,
         'learning': 6875,
         'league': 6855,
         'kolkata': 6846,
         'krishna': 6835,
         'sky': 6793,
         'street': 6787,
         'asset': 6768,
         'initiative': 6758,
         'ಕ': 6741,
         'program': 6726,
         'coalition': 6703,
         'perfect': 6703,
         'guild': 6686,
         'ನ': 6671,
         'sys': 6670,
         'n': 6651,
         'housing': 6614,
         'hair': 6605,
         'md': 6529,
         'sree': 6511,
         'charities': 6497,
         'ram': 6496,
         'committee': 6486,
         'galaxy': 6485,
         'balaji': 6473,
         'dynamics': 6456,
         'pune': 6451,
         'న': 6451,
         'martinez': 6444,
         'वर': 6444,
         'sunrise': 6436,
         'hernandez': 6377,
         'good': 6350,
         'concepts': 6302,
         'equity': 6295,
         'youth': 6282,
         'r': 6276,
         'e': 6265,
         'rodriguez': 6252,
         'fortune': 6238,
         'h': 6199,
         'companies': 6196,
         'alpha': 6170,
         'raj': 6166,
         'dream': 6157,
         'western': 6142,
         'retail': 6141,
         'सर': 6139,
         'indian': 6116,
         'industrial': 6111,
         'educational': 6105,
         'do': 6084,
         'g': 6079,
         'jay': 6066,
         'സ': 6045,
         'ss': 6041,
         'collective': 6027,
         'aditya': 6010,
         'laxmi': 5997,
         'unique': 5985,
         'lakshmi': 5979,
         'शन': 5979,
         'j': 5973,
         'brands': 5967,
         'tirupati': 5966,
         'al': 5940,
         'my': 5929,
         'shiv': 5897,
         'bharat': 5889,
         'property': 5881,
         'seven': 5874,
         'shakti': 5869,
         'ph': 5856,
         'hitech': 5837,
         'surya': 5828,
         'cafe': 5825,
         'deli': 5807,
         'য': 5805,
         'jain': 5788,
         'northern': 5761,
         'dpm': 5745,
         'baba': 5697,
         'commercial': 5695,
         'guru': 5690,
         'pizza': 5688,
         'gujarat': 5682,
         'massage': 5675,
         'shiva': 5673,
         'anand': 5664,
         'bombay': 5640,
         'seafood': 5631,
         'vijay': 5610,
         'indo': 5584,
         'insurance': 5582,
         'dmd': 5580,
         'hari': 5573,
         'arihant': 5562,
         'lotus': 5558,
         'shop': 5556,
         'design': 5533,
         'esq': 5528,
         'little': 5511,
         'swastik': 5500,
         'shyam': 5466,
         'wellness': 5459,
         'cpa': 5445,
         'seva': 5435,
         'jackson': 5397,
         'जन': 5390,
         'main': 5368,
         'shivam': 5362,
         'ક': 5332,
         'डर': 5320,
         'analytics': 5284,
         'इज': 5233,
         'motors': 5219,
         'martin': 5196,
         'ष': 5192,
         'supply': 5192,
         'grill': 5182,
         'charitable': 5150,
         'cénter': 5144,
         'ச': 5120,
         'lopez': 5114,
         'ন': 5108,
         'ई': 5105,
         'freight': 5097,
         'chemical': 5070,
         'जय': 5070,
         'practice': 5006,
         'ન': 5001,
         'gonzalez': 4982,
         'mortgage': 4975,
         'board': 4941,
         'nursing': 4933,
         'commission': 4921,
         'chennai': 4913,
         'upper': 4907,
         'ಯ': 4888,
         'anderson': 4884,
         'ఫ': 4873,
         'इट': 4851,
         'hyderabad': 4843,
         'happy': 4819,
         'ক': 4807,
         'wireless': 4806,
         'st': 4801,
         'wilson': 4776,
         'coffee': 4775,
         'cargo': 4768,
         'chambers': 4766,
         'steel': 4766,
         'ice': 4742,
         'samiti': 4734,
         'इम': 4725,
         'एस': 4719,
         'up': 4718,
         'charter': 4714,
         'consumer': 4709,
         'i': 4703,
         'lucky': 4696,
         'గ': 4688,
         'पर': 4667,
         'lower': 4656,
         'textiles': 4645,
         'टरन': 4616,
         'शनल': 4616,
         'twisted': 4549,
         'sangh': 4546,
         'farms': 4538,
         'lee': 4528,
         'बल': 4527,
         'thomas': 4516,
         'taylor': 4505,
         'book': 4499,
         'restaurant': 4497,
         'corner': 4444,
         'ಫ': 4442,
         'printing': 4439,
         'general': 4423,
         'sweet': 4402,
         'ன': 4395,
         'ಗ': 4387,
         'veterans': 4360,
         'body': 4359,
         'moore': 4355,
         'cozy': 4339,
         'maid': 4312,
         'rev': 4304,
         'edge': 4301,
         'perez': 4290,
         'diner': 4283,
         'straight': 4282,
         'pub': 4278,
         'hill': 4266,
         'bike': 4261,
         'marine': 4253,
         'entertainment': 4250,
         'vidyalaya': 4246,
         'polytechnic': 4234,
         'pharmaceuticals': 4221,
         'staffing': 4214,
         'no': 4174,
         'జ': 4167,
         'arts': 4162,
         'baptist': 4153,
         'resources': 4146,
         'apparel': 4145,
         'store': 4138,
         'टल': 4131,
         'back': 4124,
         'packaging': 4102,
         'veterinary': 4069,
         'tavern': 4058,
         'road': 4040,
         'u': 4031,
         'king': 4027,
         'on': 4017,
         'wholesale': 4017,
         'park': 4009,
         'dent': 3995,
         'hypnosis': 3993,
         'ய': 3991,
         'yoga': 3979,
         'tattoo': 3978,
         'barbershop': 3973,
         'thompson': 3928,
         'montessori': 3906,
         'iii': 3844,
         'wealth': 3835,
         'ട': 3826,
         'harris': 3824,
         'alley': 3815,
         'transport': 3804,
         'holding': 3796,
         'ଟ': 3785,
         'nails': 3781,
         'pilates': 3775,
         'y': 3757,
         'human': 3756,
         'bistro': 3746,
         'య': 3739,
         'sanchez': 3735,
         'mobility': 3733,
         'owners': 3727,
         'telecom': 3717,
         'metal': 3717,
         'डस': 3711,
         'cloud': 3711,
         'tax': 3707,
         'q': 3689,
         'z': 3670,
         'cream': 3669,
         'ଲ': 3668,
         'ગ': 3658,
         'sérvices': 3651,
         'trinity': 3650,
         'ஃப': 3649,
         'lane': 3644,
         '5': 3632,
         'ए': 3629,
         'टरप': 3629,
         'bureau': 3625,
         'ଡ': 3625,
         'ର': 3623,
         'preparatory': 3613,
         'ମ': 3608,
         'technical': 3607,
         'department': 3587,
         'intelligence': 3551,
         'ಜ': 3541,
         'heart': 3533,
         'fashion': 3521,
         'lnc': 3521,
         'ઇન': 3503,
         'x': 3481,
         'यन': 3478,
         'vi': 3476,
         'लक': 3462,
         'assets': 3460,
         'communications': 3438,
         'county': 3428,
         'ii': 3427,
         'agricultural': 3423,
         'aerospace': 3413,
         'clark': 3410,
         'यल': 3408,
         'ପ': 3408,
         'ईस': 3405,
         'ব': 3394,
         'agencies': 3389,
         'अर': 3388,
         'corporate': 3382,
         'literacy': 3369,
         'ਲ': 3364,
         'engineers': 3352,
         'hall': 3346,
         'iv': 3346,
         'defense': 3334,
         'वन': 3329,
         'ફ': 3325,
         'payment': 3323,
         'अल': 3320,
         'cancer': 3309,
         'building': 3299,
         'economic': 3287,
         'pártners': 3282,
         'hotels': 3275,
         'robotics': 3274,
         'pediatrics': 3273,
         'division': 3270,
         'solution': 3252,
         'lewis': 3243,
         'manufacturing': 3242,
         'children': 3241,
         'endocrinology': 3240,
         'ਰ': 3237,
         'materials': 3232,
         'semiconductor': 3230,
         '7': 3221,
         'ánd': 3217,
         '2': 3216,
         'sales': 3216,
         'interfaith': 3209,
         'índia': 3205,
         'advisory': 3201,
         'biomedical': 3197,
         'ય': 3193,
         'cáre': 3188,
         'robinson': 3179,
         'lake': 3172,
         'fitness': 3168,
         'एनर': 3149,
         'automation': 3143,
         'furniture': 3140,
         '6': 3135,
         'stores': 3132,
         'sciences': 3129,
         'young': 3128,
         'mills': 3117,
         'wildlife': 3113,
         'biotech': 3112,
         'இன': 3110,
         'jaipur': 3108,
         'ஜ': 3105,
         '4': 3100,
         '8': 3094,
         'जम': 3092,
         'टव': 3067,
         'आईट': 3056,
         'ക': 3055,
         'ramirez': 3053,
         'थक': 3041,
         'cultural': 3038,
         '9': 3037,
         'scholarship': 3029,
         'एग': 3022,
         'textile': 3020,
         'hunger': 3017,
         'वलपर': 3016,
         'autism': 3008,
         'उ': 3003,
         'डक': 3001,
         'ଇଭ': 2993,
         'सप': 2992,
         'एक': 2992,
         'saint': 2989,
         '3': 2984,
         'historical': 2982,
         'walker': 2980,
         'ਪ': 2974,
         'spa': 2971,
         'iron': 2970,
         'ਡ': 2963,
         'morgan': 2955,
         'વ': 2954,
         'glass': 2952,
         'allen': 2946,
         'જ': 2929,
         'pharma': 2913,
         'wright': 2904,
         'rights': 2904,
         'electric': 2901,
         'బ': 2899,
         'apartments': 2858,

In [72]:
thresholds = [100, 500, 1000, 5000, 10000, 25000, 50000]

print("S2 tokens surviving each threshold")
print("-" * 50)

for threshold in thresholds:
    count = sum(
        freq <= threshold
        for freq in s2_token_frequency.values()
    )
    print(f"<= {threshold:>6}: {count:,} tokens")

print("\nS3 tokens surviving each threshold")
print("-" * 50)

for threshold in thresholds:
    count = sum(
        freq <= threshold
        for freq in s3_token_frequency.values()
    )
    print(f"<= {threshold:>6}: {count:,} tokens")

S2 tokens surviving each threshold
--------------------------------------------------
<=    100: 801,413 tokens
<=    500: 807,680 tokens
<=   1000: 808,972 tokens
<=   5000: 809,965 tokens
<=  10000: 810,176 tokens
<=  25000: 810,411 tokens
<=  50000: 810,474 tokens

S3 tokens surviving each threshold
--------------------------------------------------
<=    100: 853,517 tokens
<=    500: 860,216 tokens
<=   1000: 861,464 tokens
<=   5000: 862,459 tokens
<=  10000: 862,668 tokens
<=  25000: 862,936 tokens
<=  50000: 862,972 tokens

In [73]:
def useful_tokens(name, frequency, threshold):
    normalized = normalize_text(name)

    if not normalized:
        return []

    return [
        token
        for token in set(normalized.split())
        if frequency.get(token, 0) <= threshold
    ]

In [74]:
for threshold in thresholds:
    usable = 0
    total_tokens = 0

    for name in s1_val["business_name"]:
        tokens = useful_tokens(
            name,
            s2_token_frequency,
            threshold
        )

        if tokens:
            usable += 1
            total_tokens += len(tokens)

    print(
        f"Threshold {threshold:>6}: "
        f"{usable:,} / {len(s1_val):,} S1 records have "
        f"at least one usable token | "
        f"avg usable tokens = "
        f"{total_tokens / len(s1_val):.2f}"
    )

Threshold    100: 136,523 / 415,946 S1 records have at least one usable token | avg usable tokens = 0.37
Threshold    500: 199,434 / 415,946 S1 records have at least one usable token | avg usable tokens = 0.59
Threshold   1000: 241,727 / 415,946 S1 records have at least one usable token | avg usable tokens = 0.82
Threshold   5000: 335,261 / 415,946 S1 records have at least one usable token | avg usable tokens = 1.27
Threshold  10000: 367,933 / 415,946 S1 records have at least one usable token | avg usable tokens = 1.52
Threshold  25000: 414,286 / 415,946 S1 records have at least one usable token | avg usable tokens = 2.24
Threshold  50000: 415,910 / 415,946 S1 records have at least one usable token | avg usable tokens = 2.40

In [75]:
TOKEN_FREQ_THRESHOLD = 25_000

def build_filtered_token_index(
    path,
    token_frequency,
    max_frequency=25_000,
    chunk_size=200_000
):
    index = defaultdict(set)

    total_rows = 0
    kept_tokens = 0

    allowed_tokens = {
        token
        for token, freq in token_frequency.items()
        if freq <= max_frequency
    }

    print("Allowed tokens:", len(allowed_tokens))

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=["entity_id", "business_name"],
        chunksize=chunk_size
    ):
        total_rows += len(chunk)

        for entity_id, name in zip(
            chunk["entity_id"],
            chunk["business_name"]
        ):
            normalized = normalize_text(name)

            if not normalized:
                continue

            tokens = set(normalized.split())

            for token in tokens:
                if token in allowed_tokens:
                    index[token].add(entity_id)

        print(f"Processed {total_rows:,} rows...")

    print(
        f"Finished. Index contains {len(index):,} tokens."
    )

    return index

In [76]:
start = perf_counter()

s2_filtered_token_index = build_filtered_token_index(
    S2_PATH,
    s2_token_frequency,
    max_frequency=TOKEN_FREQ_THRESHOLD
)

print(
    f"\nS2 filtered token index built in "
    f"{perf_counter() - start:.2f} seconds"
)

Allowed tokens: 810411
Processed 200,000 rows...
Processed 400,000 rows...
Processed 600,000 rows...
Processed 800,000 rows...
Processed 1,000,000 rows...
Processed 1,200,000 rows...
Processed 1,400,000 rows...
Processed 1,600,000 rows...
Processed 1,800,000 rows...
Processed 2,000,000 rows...
Processed 2,200,000 rows...
Processed 2,400,000 rows...
Processed 2,600,000 rows...
Processed 2,800,000 rows...
Processed 3,000,000 rows...
Processed 3,200,000 rows...
Processed 3,400,000 rows...
Processed 3,600,000 rows...
Processed 3,800,000 rows...
Processed 4,000,000 rows...
Processed 4,200,000 rows...
Processed 4,400,000 rows...
Processed 4,600,000 rows...
Processed 4,800,000 rows...
Processed 5,000,000 rows...
Processed 5,034,616 rows...
Finished. Index contains 810,411 tokens.

S2 filtered token index built in 75.40 seconds

In [77]:
start = perf_counter()

s3_filtered_token_index = build_filtered_token_index(
    S3_PATH,
    s3_token_frequency,
    max_frequency=TOKEN_FREQ_THRESHOLD
)

print(
    f"\nS3 filtered token index built in "
    f"{perf_counter() - start:.2f} seconds"
)

Allowed tokens: 862936
Processed 200,000 rows...
Processed 400,000 rows...
Processed 600,000 rows...
Processed 800,000 rows...
Processed 1,000,000 rows...
Processed 1,200,000 rows...
Processed 1,400,000 rows...
Processed 1,600,000 rows...
Processed 1,800,000 rows...
Processed 2,000,000 rows...
Processed 2,200,000 rows...
Processed 2,400,000 rows...
Processed 2,600,000 rows...
Processed 2,800,000 rows...
Processed 3,000,000 rows...
Processed 3,200,000 rows...
Processed 3,400,000 rows...
Processed 3,600,000 rows...
Processed 3,800,000 rows...
Processed 4,000,000 rows...
Processed 4,200,000 rows...
Processed 4,400,000 rows...
Processed 4,600,000 rows...
Processed 4,800,000 rows...
Processed 5,000,000 rows...
Processed 5,200,000 rows...
Processed 5,285,603 rows...
Finished. Index contains 862,936 tokens.

S3 filtered token index built in 54.72 seconds

In [78]:
def evaluate_filtered_token_block(
    s1_df,
    s2_index,
    s3_index,
    val_gt,
    max_s1=None
):

    total_candidates = 0
    s1_with_candidates = 0

    per_s1_counts = []

    recall_sum = 0.0
    evaluated = 0
    skipped = 0

    for i, (_, row) in enumerate(s1_df.iterrows()):

        if max_s1 is not None and i >= max_s1:
            break

        s1_id = row["entity_id"]

        normalized = normalize_text(row["business_name"])

        if not normalized:
            candidate_ids = set()
        else:
            tokens = set(normalized.split())

            candidate_ids = set()

            for token in tokens:
                candidate_ids.update(
                    s2_index.get(token, set())
                )
                candidate_ids.update(
                    s3_index.get(token, set())
                )

        n_candidates = len(candidate_ids)

        total_candidates += n_candidates

        if n_candidates > 0:
            s1_with_candidates += 1

        per_s1_counts.append(n_candidates)

        # Recall
        if s1_id not in val_gt:
            skipped += 1
        else:
            true_matches = val_gt[s1_id]

            if len(true_matches) == 0:
                recall_sum += 1.0
            else:
                found = len(
                    true_matches & candidate_ids
                )

                recall_sum += (
                    found / len(true_matches)
                )

            evaluated += 1

        if (i + 1) % 10_000 == 0:
            print(
                f"Processed {i + 1:,} S1 records | "
                f"candidates so far: {total_candidates:,}"
            )

    import numpy as np

    counts = np.array(per_s1_counts)

    result = {
        "total_candidate_pairs": total_candidates,
        "s1_records_with_candidates": s1_with_candidates,
        "average_candidates_per_s1": counts.mean(),
        "median_candidates_per_s1": np.median(counts),
        "p95_candidates_per_s1": np.quantile(counts, 0.95),
        "p99_candidates_per_s1": np.quantile(counts, 0.99),
        "max_candidates_per_s1": counts.max(),
        "macro_candidate_recall": (
            recall_sum / evaluated
            if evaluated > 0 else 0.0
        ),
        "n_evaluated": evaluated,
        "n_skipped_no_ground_truth": skipped,
    }

    return result

In [79]:
print(evaluate_filtered_token_block)

<function evaluate_filtered_token_block at 0x000001A1FB8909A0>

In [80]:
start = perf_counter()

token_test_10k = evaluate_filtered_token_block(
    s1_df=s1_val,
    s2_index=s2_filtered_token_index,
    s3_index=s3_filtered_token_index,
    val_gt=val_gt,
    max_s1=10_000
)

print("\n10K TOKEN BLOCK TEST")
print("-" * 50)

for key, value in token_test_10k.items():
    print(f"{key}: {value}")

print(f"\nTime: {perf_counter() - start:.2f} seconds")

Processed 10,000 S1 records | candidates so far: 287,405,386

10K TOKEN BLOCK TEST
--------------------------------------------------
total_candidate_pairs: 287405386
s1_records_with_candidates: 9964
average_candidates_per_s1: 28740.5386
median_candidates_per_s1: 27352.0
p95_candidates_per_s1: 71824.49999999997
p99_candidates_per_s1: 89596.50000000001
max_candidates_per_s1: 135217
macro_candidate_recall: 0.8507466031445877
n_evaluated: 9998
n_skipped_no_ground_truth: 2

Time: 37.27 seconds

In [81]:
del s2_filtered_token_index
del s3_filtered_token_index

import gc
gc.collect()

print("25k token indexes removed from memory.")

25k token indexes removed from memory.

In [82]:
TOKEN_FREQ_THRESHOLD = 5_000

print("Testing token frequency threshold:", TOKEN_FREQ_THRESHOLD)

Testing token frequency threshold: 5000

In [83]:
start = perf_counter()

s2_filtered_token_index = build_filtered_token_index(
    S2_PATH,
    s2_token_frequency,
    max_frequency=TOKEN_FREQ_THRESHOLD
)

print(
    f"\nS2 5k token index built in "
    f"{perf_counter() - start:.2f} seconds"
)

Allowed tokens: 809965
Processed 200,000 rows...
Processed 400,000 rows...
Processed 600,000 rows...
Processed 800,000 rows...
Processed 1,000,000 rows...
Processed 1,200,000 rows...
Processed 1,400,000 rows...
Processed 1,600,000 rows...
Processed 1,800,000 rows...
Processed 2,000,000 rows...
Processed 2,200,000 rows...
Processed 2,400,000 rows...
Processed 2,600,000 rows...
Processed 2,800,000 rows...
Processed 3,000,000 rows...
Processed 3,200,000 rows...
Processed 3,400,000 rows...
Processed 3,600,000 rows...
Processed 3,800,000 rows...
Processed 4,000,000 rows...
Processed 4,200,000 rows...
Processed 4,400,000 rows...
Processed 4,600,000 rows...
Processed 4,800,000 rows...
Processed 5,000,000 rows...
Processed 5,034,616 rows...
Finished. Index contains 809,965 tokens.

S2 5k token index built in 51.28 seconds

In [84]:
start = perf_counter()

s3_filtered_token_index = build_filtered_token_index(
    S3_PATH,
    s3_token_frequency,
    max_frequency=TOKEN_FREQ_THRESHOLD
)

print(
    f"\nS3 5k token index built in "
    f"{perf_counter() - start:.2f} seconds"
)

Allowed tokens: 862459
Processed 200,000 rows...
Processed 400,000 rows...
Processed 600,000 rows...
Processed 800,000 rows...
Processed 1,000,000 rows...
Processed 1,200,000 rows...
Processed 1,400,000 rows...
Processed 1,600,000 rows...
Processed 1,800,000 rows...
Processed 2,000,000 rows...
Processed 2,200,000 rows...
Processed 2,400,000 rows...
Processed 2,600,000 rows...
Processed 2,800,000 rows...
Processed 3,000,000 rows...
Processed 3,200,000 rows...
Processed 3,400,000 rows...
Processed 3,600,000 rows...
Processed 3,800,000 rows...
Processed 4,000,000 rows...
Processed 4,200,000 rows...
Processed 4,400,000 rows...
Processed 4,600,000 rows...
Processed 4,800,000 rows...
Processed 5,000,000 rows...
Processed 5,200,000 rows...
Processed 5,285,603 rows...
Finished. Index contains 862,459 tokens.

S3 5k token index built in 50.91 seconds

In [85]:
start = perf_counter()

token_test_5k = evaluate_filtered_token_block(
    s1_df=s1_val,
    s2_index=s2_filtered_token_index,
    s3_index=s3_filtered_token_index,
    val_gt=val_gt,
    max_s1=10_000
)

print("\n10K TOKEN BLOCK TEST — 5K THRESHOLD")
print("-" * 50)

for key, value in token_test_5k.items():
    print(f"{key}: {value}")

print(f"\nTime: {perf_counter() - start:.2f} seconds")

Processed 10,000 S1 records | candidates so far: 26,629,368

10K TOKEN BLOCK TEST — 5K THRESHOLD
--------------------------------------------------
total_candidate_pairs: 26629368
s1_records_with_candidates: 8096
average_candidates_per_s1: 2662.9368
median_candidates_per_s1: 1711.0
p95_candidates_per_s1: 9285.499999999993
p99_candidates_per_s1: 14886.01
max_candidates_per_s1: 24366
macro_candidate_recall: 0.6618823223519209
n_evaluated: 9998
n_skipped_no_ground_truth: 2

Time: 3.95 seconds

In [86]:
def rarest_token_block(
    s1_df,
    s2_index,
    s3_index,
    s2_frequency,
    s3_frequency,
    val_gt,
    max_frequency=5_000,
    max_s1=None
):
    total_candidates = 0
    s1_with_candidates = 0
    per_s1_counts = []

    recall_sum = 0.0
    evaluated = 0
    skipped = 0

    for i, (_, row) in enumerate(s1_df.iterrows()):

        if max_s1 is not None and i >= max_s1:
            break

        s1_id = row["entity_id"]
        normalized = normalize_text(row["business_name"])

        if not normalized:
            candidate_ids = set()

        else:
            tokens = set(normalized.split())

            # Keep only tokens that exist in at least one index
            usable = []

            for token in tokens:

                freq_s2 = s2_frequency.get(token, float("inf"))
                freq_s3 = s3_frequency.get(token, float("inf"))

                freq = min(freq_s2, freq_s3)

                if freq <= max_frequency:
                    usable.append((token, freq))

            if not usable:
                candidate_ids = set()

            else:
                # Choose the rarest token
                rarest_token, _ = min(
                    usable,
                    key=lambda x: x[1]
                )

                candidate_ids = set()

                candidate_ids.update(
                    s2_index.get(rarest_token, set())
                )

                candidate_ids.update(
                    s3_index.get(rarest_token, set())
                )

        n_candidates = len(candidate_ids)

        total_candidates += n_candidates

        if n_candidates > 0:
            s1_with_candidates += 1

        per_s1_counts.append(n_candidates)

        # Recall
        if s1_id not in val_gt:
            skipped += 1

        else:
            true_matches = val_gt[s1_id]

            if len(true_matches) == 0:
                recall_sum += 1.0

            else:
                found = len(
                    true_matches & candidate_ids
                )

                recall_sum += (
                    found / len(true_matches)
                )

            evaluated += 1

        if (i + 1) % 10_000 == 0:
            print(
                f"Processed {i + 1:,} S1 records | "
                f"candidates so far: {total_candidates:,}"
            )

    import numpy as np

    counts = np.array(per_s1_counts)

    return {
        "total_candidate_pairs": total_candidates,
        "s1_records_with_candidates": s1_with_candidates,
        "average_candidates_per_s1": counts.mean(),
        "median_candidates_per_s1": np.median(counts),
        "p95_candidates_per_s1": np.quantile(counts, 0.95),
        "p99_candidates_per_s1": np.quantile(counts, 0.99),
        "max_candidates_per_s1": counts.max(),
        "macro_candidate_recall": (
            recall_sum / evaluated
            if evaluated else 0.0
        ),
        "n_evaluated": evaluated,
        "n_skipped_no_ground_truth": skipped,
    }

In [87]:
rarest_token_test = rarest_token_block(
    s1_df=s1_val,
    s2_index=s2_filtered_token_index,
    s3_index=s3_filtered_token_index,
    s2_frequency=s2_token_frequency,
    s3_frequency=s3_token_frequency,
    val_gt=val_gt,
    max_frequency=5_000,
    max_s1=10_000
)

print("\nRAREST NAME TOKEN — 5K")
print("-" * 50)

for key, value in rarest_token_test.items():
    print(f"{key}: {value}")

Processed 10,000 S1 records | candidates so far: 12,933,582

RAREST NAME TOKEN — 5K
--------------------------------------------------
total_candidate_pairs: 12933582
s1_records_with_candidates: 8096
average_candidates_per_s1: 1293.3582
median_candidates_per_s1: 179.0
p95_candidates_per_s1: 6295.0
p99_candidates_per_s1: 8500.0
max_candidates_per_s1: 9772
macro_candidate_recall: 0.6361925812290935
n_evaluated: 9998
n_skipped_no_ground_truth: 2

In [88]:
def normalize_address(value):
    if pd.isna(value):
        return ""

    value = str(value)

    value = unicodedata.normalize("NFKC", value)
    value = value.lower()

    value = re.sub(r"[^\w\s]", " ", value)

    value = re.sub(r"\s+", " ", value).strip()

    return value

In [89]:
s1_val["address_norm"] = (
    s1_val["business_address"]
    .map(normalize_address)
)

print(
    "Validation S1 with non-empty addresses:",
    (s1_val["address_norm"] != "").sum()
)

s1_val[
    ["business_name", "business_address", "address_norm"]
].head(10)

Validation S1 with non-empty addresses: 415946

,business_name,business_address,address_norm
10,Crystal Lending PC,"11643 Prosperity Road, South Jordan, UT",11643 prosperity road south jordan ut
13,Helios,"66 Edgewood Street, Bridgeport, CT",66 edgewood street bridgeport ct
16,Smart Healthcare Private Limited,"303, 3Rd Floor Sakar 5 B/H Natraj Cinema Ashra...",303 3rd floor sakar 5 b h natraj cinema ashram...
29,Pacific Learning Laboratories LLC,"4810 Nassau Avenue, Sand Springs, OK",4810 nassau avenue sand springs ok
33,Apex Inc,"108 Richardson Street, Bethany, WV",108 richardson street bethany wv
34,Foot & Ankle Allied Center LLC,"1216 Preston Avenue, Charlottesville City, VA",1216 preston avenue charlottesville city va
37,FUE Pgim Care,"211 Dewey Road, IL, Rockton",211 dewey road il rockton
38,Primary Care Physicians Inc.,"53 Park Lane, Wellsville, NY",53 park lane wellsville ny
41,George Saul Inc,"Unit UNIT 367, 1400 Great Wolf Drive, WI, Vill...",unit unit 367 1400 great wolf drive wi village...
54,Abhushan & Brothers Co,"Hig 28 1St Floor Indra Nagar, Kanpur, Uttar Pr...",hig 28 1st floor indra nagar kanpur uttar pradesh

In [90]:
for address in s1_val["address_norm"].head(20):
    print(address)

11643 prosperity road south jordan ut
66 edgewood street bridgeport ct
303 3rd floor sakar 5 b h natraj cinema ashram road ahmedabad gujarat
4810 nassau avenue sand springs ok
108 richardson street bethany wv
1216 preston avenue charlottesville city va
211 dewey road il rockton
53 park lane wellsville ny
unit unit 367 1400 great wolf drive wi village of lake delton
hig 28 1st floor indra nagar kanpur uttar pradesh
west bengal howrah 229 kolkata netaji subhas chandra bose road vishnu enclave 3rd floor flat no 3a kolkata
a 1 malad west mumbai maharashtra 401 rahul apartment marve road
109 2 floor 16 cross road jp nagar phase 4 dollars bangalore south bangalore karnataka
1204 block c stratum venus ground nr jhansi ki rani statue nehrunagar ahmadabad city ahmedabad gujarat
28 b chand bihari nagar near khatipura bridge khatipura jaipur rajasthan
9 2113 gali no 7 kailash nagar new delhi east delhi delhi
122 dayton yellow springs road unit 4 fairborn oh
37197 sandy ridge drive north ridgeville oh
207 marley neck road fl 0 glen burnie md
174 stover road de queen ar

In [91]:
from collections import defaultdict

def build_full_address_index(path, chunk_size=200_000):

    index = defaultdict(set)
    total_rows = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=["entity_id", "business_address"],
        chunksize=chunk_size
    ):
        total_rows += len(chunk)

        chunk["address_norm"] = (
            chunk["business_address"]
            .map(normalize_address)
        )

        chunk = chunk[
            chunk["address_norm"] != ""
        ]

        for address, group in chunk.groupby("address_norm"):
            index[address].update(
                group["entity_id"].tolist()
            )

        print(f"Processed {total_rows:,} rows...")

    print(
        f"Finished. Index contains "
        f"{len(index):,} normalized addresses."
    )

    return index

In [92]:
start = perf_counter()

s2_address_index = build_full_address_index(
    S2_PATH
)

print(
    f"S2 address index built in "
    f"{perf_counter() - start:.2f} seconds"
)

Processed 200,000 rows...
Processed 400,000 rows...
Processed 600,000 rows...
Processed 800,000 rows...
Processed 1,000,000 rows...
Processed 1,200,000 rows...
Processed 1,400,000 rows...
Processed 1,600,000 rows...
Processed 1,800,000 rows...
Processed 2,000,000 rows...
Processed 2,200,000 rows...
Processed 2,400,000 rows...
Processed 2,600,000 rows...
Processed 2,800,000 rows...
Processed 3,000,000 rows...
Processed 3,200,000 rows...
Processed 3,400,000 rows...
Processed 3,600,000 rows...
Processed 3,800,000 rows...
Processed 4,000,000 rows...
Processed 4,200,000 rows...
Processed 4,400,000 rows...
Processed 4,600,000 rows...
Processed 4,800,000 rows...
Processed 5,000,000 rows...
Processed 5,034,616 rows...
Finished. Index contains 4,286,077 normalized addresses.
S2 address index built in 336.15 seconds

In [93]:
start = perf_counter()

s3_address_index = build_full_address_index(
    S3_PATH
)

print(
    f"S3 address index built in "
    f"{perf_counter() - start:.2f} seconds"
)

Processed 200,000 rows...
Processed 400,000 rows...
Processed 600,000 rows...
Processed 800,000 rows...
Processed 1,000,000 rows...
Processed 1,200,000 rows...
Processed 1,400,000 rows...
Processed 1,600,000 rows...
Processed 1,800,000 rows...
Processed 2,000,000 rows...
Processed 2,200,000 rows...
Processed 2,400,000 rows...
Processed 2,600,000 rows...
Processed 2,800,000 rows...
Processed 3,000,000 rows...
Processed 3,200,000 rows...
Processed 3,400,000 rows...
Processed 3,600,000 rows...
Processed 3,800,000 rows...
Processed 4,000,000 rows...
Processed 4,200,000 rows...
Processed 4,400,000 rows...
Processed 4,600,000 rows...
Processed 4,800,000 rows...
Processed 5,000,000 rows...
Processed 5,200,000 rows...
Processed 5,285,603 rows...
Finished. Index contains 4,616,044 normalized addresses.
S3 address index built in 244.47 seconds

In [94]:
def evaluate_exact_address_block(
    s1_df,
    s2_index,
    s3_index,
    val_gt,
    max_s1=None
):

    total_candidates = 0
    s1_with_candidates = 0
    per_s1_counts = []

    recall_sum = 0.0
    evaluated = 0
    skipped = 0

    for i, (_, row) in enumerate(s1_df.iterrows()):

        if max_s1 is not None and i >= max_s1:
            break

        s1_id = row["entity_id"]
        address = normalize_address(
            row["business_address"]
        )

        candidate_ids = set()

        if address:
            candidate_ids.update(
                s2_index.get(address, set())
            )

            candidate_ids.update(
                s3_index.get(address, set())
            )

        n_candidates = len(candidate_ids)

        total_candidates += n_candidates

        if n_candidates > 0:
            s1_with_candidates += 1

        per_s1_counts.append(n_candidates)

        # Candidate recall
        if s1_id not in val_gt:
            skipped += 1

        else:
            true_matches = val_gt[s1_id]

            if len(true_matches) == 0:
                recall_sum += 1.0

            else:
                found = len(
                    true_matches & candidate_ids
                )

                recall_sum += (
                    found / len(true_matches)
                )

            evaluated += 1

        if (i + 1) % 10_000 == 0:
            print(
                f"Processed {i + 1:,} S1 records | "
                f"candidates so far: "
                f"{total_candidates:,}"
            )

    import numpy as np

    counts = np.array(per_s1_counts)

    return {
        "total_candidate_pairs": total_candidates,
        "s1_records_with_candidates": s1_with_candidates,
        "average_candidates_per_s1": counts.mean(),
        "median_candidates_per_s1": np.median(counts),
        "p95_candidates_per_s1": np.quantile(counts, 0.95),
        "p99_candidates_per_s1": np.quantile(counts, 0.99),
        "max_candidates_per_s1": counts.max(),
        "macro_candidate_recall": (
            recall_sum / evaluated
            if evaluated else 0.0
        ),
        "n_evaluated": evaluated,
        "n_skipped_no_ground_truth": skipped
    }

In [95]:
address_test_10k = evaluate_exact_address_block(
    s1_df=s1_val,
    s2_index=s2_address_index,
    s3_index=s3_address_index,
    val_gt=val_gt,
    max_s1=10_000
)

print("\nEXACT NORMALIZED ADDRESS - 10K TEST")
print("-" * 55)

for key, value in address_test_10k.items():
    print(f"{key}: {value}")

Processed 10,000 S1 records | candidates so far: 3,367

EXACT NORMALIZED ADDRESS - 10K TEST
-------------------------------------------------------
total_candidate_pairs: 3367
s1_records_with_candidates: 2373
average_candidates_per_s1: 0.3367
median_candidates_per_s1: 0.0
p95_candidates_per_s1: 2.0
p99_candidates_per_s1: 3.0
max_candidates_per_s1: 13
macro_candidate_recall: 0.13180100666598035
n_evaluated: 9998
n_skipped_no_ground_truth: 2

In [96]:
def extract_address_numbers(value):
    if pd.isna(value):
        return set()

    text = str(value).lower()

    return set(
        re.findall(r"\b\d+[a-z]?\b", text)
    )

In [97]:
for address in s1_val["business_address"].head(20):
    print(
        address,
        "→",
        extract_address_numbers(address)
    )

11643 Prosperity Road, South Jordan, UT → {'11643'}
66 Edgewood Street, Bridgeport, CT → {'66'}
303, 3Rd Floor Sakar 5 B/H Natraj Cinema Ashram Road, Ahmedabad, Gujarat → {'303', '5'}
4810 Nassau Avenue, Sand Springs, OK → {'4810'}
108 Richardson Street, Bethany, WV → {'108'}
1216 Preston Avenue, Charlottesville City, VA → {'1216'}
211 Dewey Road, IL, Rockton → {'211'}
53 Park Lane, Wellsville, NY → {'53'}
Unit UNIT 367, 1400 Great Wolf Drive, WI, Village Of Lake Delton → {'367', '1400'}
Hig 28 1St Floor Indra Nagar, Kanpur, Uttar Pradesh → {'28'}
West Bengal, Howrah, 229, Kolkata, Netaji Subhas Chandra Bose Road Vishnu Enclave, 3Rd Floor, Flat No.- 3A, Kolkata → {'3a', '229'}
A-1, Malad (West), Mumbai, Maharashtra, 401, Rahul Apartment, Marve Road → {'1', '401'}
109 2 Floor 16 Cross Road, Jp Nagar Phase 4, Dollars, Bangalore South, Bangalore, Karnataka → {'109', '16', '4', '2'}
1204, Block-C, Stratum @ Venus Ground, Nr. Jhansi Ki Rani Statue, Nehrunagar, Ahmadabad City, Ahmedabad, Gujarat → {'1204'}
28-B, Chand Bihari Nagar Near Khatipura Bridge Khatipura, Jaipur, Rajasthan → {'28'}
9/2113, Gali No.-7 Kailash Nagar, New Delhi, East Delhi, Delhi → {'2113', '7', '9'}
122 Dayton Yellow Springs Road, Unit 4, Fairborn, OH → {'122', '4'}
37197 Sandy Ridge Drive, North Ridgeville, OH → {'37197'}
207 Marley Neck Road, Fl 0, Glen Burnie, MD → {'207', '0'}
174 Stover Road, De Queen, AR → {'174'}

In [98]:
s1_val["address_numbers"] = (
    s1_val["business_address"]
    .map(extract_address_numbers)
)

print(
    "S1 records with at least one address number:",
    (s1_val["address_numbers"].map(len) > 0).sum()
)

s1_val[
    ["business_address", "address_numbers"]
].head(20)

S1 records with at least one address number: 395773

                                      business_address  address_numbers
10             11643 Prosperity Road, South Jordan, UT          {11643}
13                  66 Edgewood Street, Bridgeport, CT             {66}
16   303, 3Rd Floor Sakar 5 B/H Natraj Cinema Ashra...         {303, 5}
29                4810 Nassau Avenue, Sand Springs, OK           {4810}
33                  108 Richardson Street, Bethany, WV            {108}
34       1216 Preston Avenue, Charlottesville City, VA           {1216}
37                         211 Dewey Road, IL, Rockton            {211}
38                        53 Park Lane, Wellsville, NY             {53}
41   Unit UNIT 367, 1400 Great Wolf Drive, WI, Vill...      {367, 1400}
54   Hig 28 1St Floor Indra Nagar, Kanpur, Uttar Pr...             {28}
55   West Bengal, Howrah, 229, Kolkata, Netaji Subh...        {3a, 229}
60   A-1, Malad (West), Mumbai, Maharashtra, 401, R...         {1, 401}
68   109 2 Floor 16 Cross Road, Jp Nagar Phase 4, D...  {109, 16, 4, 2}
77   1204, Block-C, Stratum @ Venus Ground, Nr. Jha...           {1204}
79   28-B, Chand Bihari Nagar Near Khatipura Bridge...             {28}
80   9/2113, Gali No.-7 Kailash Nagar, New Delhi, E...     {2113, 7, 9}
82   122 Dayton Yellow Springs Road, Unit 4, Fairbo...         {122, 4}
84       37197 Sandy Ridge Drive, North Ridgeville, OH          {37197}
93         207 Marley Neck Road, Fl 0, Glen Burnie, MD         {207, 0}
100                      174 Stover Road, De Queen, AR            {174}

In [99]:
from collections import Counter

def build_address_number_frequency(path, chunk_size=200_000):

    frequency = Counter()
    total_rows = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=["business_address"],
        chunksize=chunk_size
    ):
        total_rows += len(chunk)

        for address in chunk["business_address"]:
            numbers = extract_address_numbers(address)

            for number in numbers:
                frequency[number] += 1

        if total_rows % 1_000_000 == 0:
            print(f"Processed {total_rows:,} rows...")

    print(
        f"Finished. Unique address numbers: "
        f"{len(frequency):,}"
    )

    return frequency

In [100]:
start = perf_counter()

s2_address_number_frequency = build_address_number_frequency(
    S2_PATH
)

print(
    f"S2 number frequency built in "
    f"{perf_counter() - start:.2f} seconds"
)

Processed 1,000,000 rows...
Processed 2,000,000 rows...
Processed 3,000,000 rows...
Processed 4,000,000 rows...
Processed 5,000,000 rows...
Finished. Unique address numbers: 96,977
S2 number frequency built in 32.16 seconds

In [101]:
start = perf_counter()

s3_address_number_frequency = build_address_number_frequency(
    S3_PATH
)

print(
    f"S3 number frequency built in "
    f"{perf_counter() - start:.2f} seconds"
)

Processed 1,000,000 rows...
Processed 2,000,000 rows...
Processed 3,000,000 rows...
Processed 4,000,000 rows...
Processed 5,000,000 rows...
Finished. Unique address numbers: 97,660
S3 number frequency built in 35.04 seconds

In [102]:
print("TOP S2 ADDRESS NUMBERS")

for number, count in s2_address_number_frequency.most_common(30):
    print(repr(number), "→", count)


print("\nTOP S3 ADDRESS NUMBERS")

for number, count in s3_address_number_frequency.most_common(30):
    print(repr(number), "→", count)

TOP S2 ADDRESS NUMBERS
'1' → 281590
'2' → 228480
'3' → 121045
'4' → 98543
'5' → 87501
'6' → 79997
'8' → 73792
'7' → 70463
'9' → 61552
'10' → 56686
'11' → 52792
'12' → 49938
'14' → 42531
'15' → 40092
'13' → 39186
'16' → 37420
'17' → 33730
'24' → 32883
'18' → 32401
'19' → 31061
'20' → 30705
'22' → 29393
'21' → 28651
'23' → 27536
'25' → 25124
'30' → 21987
'27' → 21747
'26' → 21705
'28' → 21388
'31' → 20254

TOP S3 ADDRESS NUMBERS
'1' → 309505
'2' → 238180
'3' → 126735
'4' → 100879
'5' → 89308
'6' → 81292
'8' → 75037
'7' → 71440
'9' → 62370
'10' → 57521
'11' → 52646
'12' → 50569
'14' → 43001
'15' → 40558
'13' → 39900
'24' → 38838
'16' → 37831
'17' → 34137
'18' → 32988
'20' → 31239
'19' → 31160
'22' → 29757
'21' → 29109
'23' → 27543
'0' → 27451
'25' → 25897
'26' → 22339
'30' → 22079
'27' → 22041
'28' → 21786

In [103]:
thresholds = [100, 500, 1000, 5000, 10000, 25000]

print("S2 address numbers surviving each threshold")
print("-" * 50)

for threshold in thresholds:
    count = sum(
        freq <= threshold
        for freq in s2_address_number_frequency.values()
    )
    print(f"<= {threshold:>5}: {count:,} numbers")


print("\nS3 address numbers surviving each threshold")
print("-" * 50)

for threshold in thresholds:
    count = sum(
        freq <= threshold
        for freq in s3_address_number_frequency.values()
    )
    print(f"<= {threshold:>5}: {count:,} numbers")

S2 address numbers surviving each threshold
--------------------------------------------------
<=   100: 91,046 numbers
<=   500: 95,535 numbers
<=  1000: 96,158 numbers
<=  5000: 96,796 numbers
<= 10000: 96,898 numbers
<= 25000: 96,952 numbers

S3 address numbers surviving each threshold
--------------------------------------------------
<=   100: 91,504 numbers
<=   500: 96,144 numbers
<=  1000: 96,806 numbers
<=  5000: 97,470 numbers
<= 10000: 97,568 numbers
<= 25000: 97,634 numbers

In [104]:
for threshold in thresholds:

    usable = 0

    for numbers in s1_val["address_numbers"]:

        if any(
            min(
                s2_address_number_frequency.get(
                    number,
                    float("inf")
                ),
                s3_address_number_frequency.get(
                    number,
                    float("inf")
                )
            ) <= threshold
            for number in numbers
        ):
            usable += 1

    print(
        f"Threshold {threshold:>5}: "
        f"{usable:,} / {len(s1_val):,} S1 records"
    )

Threshold   100: 55,857 / 415,946 S1 records
Threshold   500: 133,505 / 415,946 S1 records
Threshold  1000: 166,710 / 415,946 S1 records
Threshold  5000: 262,999 / 415,946 S1 records
Threshold 10000: 312,454 / 415,946 S1 records
Threshold 25000: 353,480 / 415,946 S1 records

In [105]:
from collections import defaultdict

def build_name_number_index(
    path,
    name_frequency,
    number_frequency,
    max_name_frequency=5000,
    max_number_frequency=5000,
    chunk_size=200_000
):
    index = defaultdict(set)
    total_rows = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=["entity_id", "business_name", "business_address"],
        chunksize=chunk_size
    ):
        total_rows += len(chunk)

        for _, row in chunk.iterrows():

            entity_id = row["entity_id"]

            name = normalize_text(row["business_name"])
            address = row["business_address"]

            if not name:
                continue

            tokens = set(name.split())
            numbers = extract_address_numbers(address)

            usable_tokens = [
                token
                for token in tokens
                if name_frequency.get(
                    token,
                    float("inf")
                ) <= max_name_frequency
            ]

            usable_numbers = [
                number
                for number in numbers
                if number_frequency.get(
                    number,
                    float("inf")
                ) <= max_number_frequency
            ]

            for token in usable_tokens:
                for number in usable_numbers:

                    key = (token, number)

                    index[key].add(entity_id)

        if total_rows % 1_000_000 == 0:
            print(
                f"Processed {total_rows:,} rows..."
            )

    print(
        f"Finished. Index contains "
        f"{len(index):,} (token, number) keys."
    )

    return index

In [106]:
start = perf_counter()

s2_name_number_index = build_name_number_index(
    S2_PATH,
    s2_token_frequency,
    s2_address_number_frequency,
    max_name_frequency=5000,
    max_number_frequency=5000
)

print(
    f"S2 name+number index built in "
    f"{perf_counter() - start:.2f} seconds"
)

Processed 1,000,000 rows...
Processed 2,000,000 rows...
Processed 3,000,000 rows...
Processed 4,000,000 rows...
Processed 5,000,000 rows...
Finished. Index contains 3,546,658 (token, number) keys.
S2 name+number index built in 441.73 seconds

In [107]:
start = perf_counter()

s3_name_number_index = build_name_number_index(
    S3_PATH,
    s3_token_frequency,
    s3_address_number_frequency,
    max_name_frequency=5000,
    max_number_frequency=5000
)

print(
    f"S3 name+number index built in "
    f"{perf_counter() - start:.2f} seconds"
)

Processed 1,000,000 rows...
Processed 2,000,000 rows...
Processed 3,000,000 rows...
Processed 4,000,000 rows...
Processed 5,000,000 rows...
Finished. Index contains 3,678,398 (token, number) keys.
S3 name+number index built in 321.79 seconds

In [111]:
def evaluate_name_number_block(
    s1_df,
    s2_index,
    s3_index,
    val_gt,
    name_frequency,
    number_frequency,
    max_name_frequency=5000,
    max_number_frequency=5000,
    max_s1=None
):
    import numpy as np

    total_candidates = 0
    s1_with_candidates = 0
    per_s1_counts = []

    recall_sum = 0.0
    evaluated = 0
    skipped = 0

    for i, (_, row) in enumerate(s1_df.iterrows()):

        if max_s1 is not None and i >= max_s1:
            break

        s1_id = row["entity_id"]

        name = normalize_text(row["business_name"])

        numbers = extract_address_numbers(
            row["business_address"]
        )

        candidate_ids = set()

        # -----------------------------------------
        # NAME + ADDRESS NUMBER BLOCK
        # -----------------------------------------

        if name and numbers:

            tokens = set(name.split())

            usable_tokens = [
                token
                for token in tokens
                if name_frequency.get(
                    token,
                    float("inf")
                ) <= max_name_frequency
            ]

            usable_numbers = [
                number
                for number in numbers
                if number_frequency.get(
                    number,
                    float("inf")
                ) <= max_number_frequency
            ]

            for token in usable_tokens:

                for number in usable_numbers:

                    key = (token, number)

                    candidate_ids.update(
                        s2_index.get(key, set())
                    )

                    candidate_ids.update(
                        s3_index.get(key, set())
                    )

        # -----------------------------------------
        # CANDIDATE COUNT
        # -----------------------------------------

        n_candidates = len(candidate_ids)

        total_candidates += n_candidates

        if n_candidates > 0:
            s1_with_candidates += 1

        per_s1_counts.append(n_candidates)

        # -----------------------------------------
        # CANDIDATE RECALL
        # -----------------------------------------

        if s1_id not in val_gt:

            skipped += 1

        else:

            true_matches = val_gt[s1_id]

            if len(true_matches) == 0:

                recall_sum += 1.0

            else:

                found = len(
                    true_matches & candidate_ids
                )

                recall_sum += (
                    found / len(true_matches)
                )

            evaluated += 1

        # -----------------------------------------
        # PROGRESS
        # -----------------------------------------

        if (i + 1) % 10_000 == 0:

            print(
                f"Processed {i + 1:,} S1 records | "
                f"candidates so far: "
                f"{total_candidates:,}"
            )

    # -----------------------------------------
    # SUMMARY STATISTICS
    # -----------------------------------------

    counts = np.array(per_s1_counts)

    return {
        "total_candidate_pairs": total_candidates,

        "s1_records_with_candidates":
            s1_with_candidates,

        "average_candidates_per_s1":
            counts.mean(),

        "median_candidates_per_s1":
            np.median(counts),

        "p95_candidates_per_s1":
            np.quantile(counts, 0.95),

        "p99_candidates_per_s1":
            np.quantile(counts, 0.99),

        "max_candidates_per_s1":
            counts.max(),

        "macro_candidate_recall": (
            recall_sum / evaluated
            if evaluated
            else 0.0
        ),

        "n_evaluated":
            evaluated,

        "n_skipped_no_ground_truth":
            skipped
    }

In [112]:
name_number_test = evaluate_name_number_block(
    s1_df=s1_val,
    s2_index=s2_name_number_index,
    s3_index=s3_name_number_index,
    val_gt=val_gt,
    name_frequency=s2_token_frequency,
    number_frequency=s2_address_number_frequency,
    max_name_frequency=5000,
    max_number_frequency=5000,
    max_s1=10_000
)

print("\nNAME TOKEN + ADDRESS NUMBER — 10K TEST")
print("-" * 55)

for key, value in name_number_test.items():
    print(f"{key}: {value}")

Processed 10,000 S1 records | candidates so far: 15,734

NAME TOKEN + ADDRESS NUMBER — 10K TEST
-------------------------------------------------------
total_candidate_pairs: 15734
s1_records_with_candidates: 4508
average_candidates_per_s1: 1.5734
median_candidates_per_s1: 0.0
p95_candidates_per_s1: 6.0
p99_candidates_per_s1: 11.0
max_candidates_per_s1: 26
macro_candidate_recall: 0.3489065489865643
n_evaluated: 9998
n_skipped_no_ground_truth: 2

COMPARISON TABLE

In [115]:
blocking_results = []

blocking_results.append({
    "block": "Exact normalized name",
    "recall": exact_name_recall["macro_candidate_recall"],
    "avg_candidates": 13.968,
    "median_candidates": 2.0,
    "p95_candidates": 78.0,
    "p99_candidates": 200.0,
    "max_candidates": 459
})

blocking_results.append({
    "block": "Name token <= 5k",
    "recall": 0.6618823223519209,
    "avg_candidates": 2662.9368,
    "median_candidates": 1711.0,
    "p95_candidates": 9285.5,
    "p99_candidates": 14886.01,
    "max_candidates": 24366
})

blocking_results.append({
    "block": "Name token <= 25k",
    "recall": 0.8507466031445877,
    "avg_candidates": 28740.5386,
    "median_candidates": 27352.0,
    "p95_candidates": 71824.5,
    "p99_candidates": 89596.5,
    "max_candidates": 135217
})

blocking_results.append({
    "block": "Rarest name token <= 5k",
    "recall": 0.6361525732274932,
    "avg_candidates": 1293.3583,
    "median_candidates": 179.0,
    "p95_candidates": 6295.0,
    "p99_candidates": 8500.0,
    "max_candidates": 9772
})

blocking_results.append({
    "block": "Exact normalized address",
    "recall": 0.13180100666598035,
    "avg_candidates": 0.3367,
    "median_candidates": 0.0,
    "p95_candidates": 2.0,
    "p99_candidates": 3.0,
    "max_candidates": 13
})

blocking_results.append({
    "block": "Name token + address number",
    "recall": 0.3489065489865643,
    "avg_candidates": 1.5734,
    "median_candidates": 0.0,
    "p95_candidates": 6.0,
    "p99_candidates": 11.0,
    "max_candidates": 26
})

blocking_results_df = pd.DataFrame(blocking_results)

blocking_results_df

,block,recall,avg_candidates,median_candidates,p95_candidates,p99_candidates,max_candidates
0,Exact normalized name,0.262762,13.9680,2.0,78.0,200.00,459
1,Name token <= 5k,0.661882,2662.9368,1711.0,9285.5,14886.01,24366
2,Name token <= 25k,0.850747,28740.5386,27352.0,71824.5,89596.50,135217
3,Rarest name token <= 5k,0.636153,1293.3583,179.0,6295.0,8500.00,9772
4,Exact normalized address,0.131801,0.3367,0.0,2.0,3.00,13
5,Name token + address number,0.348907,1.5734,0.0,6.0,11.00,26

In [116]:
from collections import Counter

def build_address_token_frequency(s1_df):
    counter = Counter()

    for address in s1_df["address_norm"]:
        if not address:
            continue

        tokens = set(address.split())
        counter.update(tokens)

    return counter

In [117]:
s1_address_frequency = build_address_token_frequency(s1_val)

print("Unique S1 address tokens:", len(s1_address_frequency))

print("\nTOP S1 ADDRESS TOKENS")
for token, count in s1_address_frequency.most_common(30):
    print(repr(token), "→", count)

Unique S1 address tokens: 171291

TOP S1 ADDRESS TOKENS
'road' → 86673
'no' → 68298
'street' → 58589
'drive' → 41659
'maharashtra' → 36134
'unit' → 36128
'avenue' → 35684
'floor' → 30725
'nagar' → 29572
'city' → 27757
'west' → 25064
'tx' → 24798
'1' → 24630
'delhi' → 23372
'pradesh' → 21308
'new' → 21076
'lane' → 20380
'c' → 19611
'ny' → 19185
'nc' → 18048
'2' → 17552
'a' → 17452
'plot' → 16461
'mumbai' → 16427
'b' → 16052
'oh' → 15945
'il' → 14250
'uttar' → 13928
'o' → 13476
'karnataka' → 13186

In [118]:
ADDRESS_TOKEN_FREQ_THRESHOLD = 5_000

useful_address_tokens = {
    token
    for token, count in s1_address_frequency.items()
    if count <= ADDRESS_TOKEN_FREQ_THRESHOLD
}

print("Total unique address tokens:", len(s1_address_frequency))
print(
    f"Useful address tokens (frequency <= {ADDRESS_TOKEN_FREQ_THRESHOLD}):",
    len(useful_address_tokens)
)

print("\nSample useful address tokens:")
print(list(useful_address_tokens)[:50])

Total unique address tokens: 171291
Useful address tokens (frequency <= 5000): 171194

Sample useful address tokens:
['kayampur', 'mahendergarh', 'local', 'sankhavaram', 'kodamullil', 'trikampura', '18287', 'hardaway', 'niranjan', '56rajalakshmi', '161st', 'barkeater', 'bonacker', 'birsi', 'decaro', 'baer', 'quarts', 'bridlepath', 'bellville', 'hinde', 'mast', 'taharabad', '9268', 'margutta', 'damaji', 'plotno766kamalkunjnrwatertanknewnandanvan', 'vrindavanvihar', '3069', 'sorale', '5296', 'bradshire', '26310', 'viswapuram', 'sidhhpur', 'ramsundar', 'doaba', 'tawde', '3723', 'alkapur', 'jagadeshnagar', 'mahat', 'mcorp', 'patliputra', '1795', 'idgha', 'yojan', 'festive', 'vilathikulam', 'bayside', 'dattatray']

In [119]:
usable_s1 = 0
total_usable_tokens = 0

for address in s1_val["address_norm"]:
    if not address:
        continue

    tokens = set(address.split())
    useful = tokens & useful_address_tokens

    if useful:
        usable_s1 += 1
        total_usable_tokens += len(useful)

print(
    f"S1 records with at least one useful address token: "
    f"{usable_s1:,} / {len(s1_val):,}"
)

print(
    "Average useful address tokens per S1:",
    total_usable_tokens / len(s1_val)
)

S1 records with at least one useful address token: 415,941 / 415,946
Average useful address tokens per S1: 4.9068677184057545

In [120]:
from collections import defaultdict
from time import perf_counter


def build_filtered_address_token_index(
    path,
    useful_tokens,
    chunk_size=200_000
):
    index = defaultdict(set)
    total_rows = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=["entity_id", "business_address"],
        chunksize=chunk_size
    ):
        total_rows += len(chunk)

        chunk["address_norm"] = (
            chunk["business_address"]
            .fillna("")
            .map(normalize_text)
        )

        for _, row in chunk.iterrows():

            address = row["address_norm"]

            if not address:
                continue

            tokens = set(address.split()) & useful_tokens

            for token in tokens:
                index[token].add(row["entity_id"])

        if total_rows % 1_000_000 < chunk_size:
            print(f"Processed {total_rows:,} rows...")

    print(f"Finished. Index contains {len(index):,} tokens.")

    return index

In [121]:
start = perf_counter()

s2_address_token_index = build_filtered_address_token_index(
    S2_PATH,
    useful_address_tokens
)

print(
    f"S2 address-token index built in "
    f"{perf_counter() - start:.2f} seconds"
)

Processed 1,000,000 rows...
Processed 2,000,000 rows...
Processed 3,000,000 rows...
Processed 4,000,000 rows...
Processed 5,000,000 rows...
Processed 5,034,616 rows...
Finished. Index contains 165,364 tokens.
S2 address-token index built in 338.07 seconds

In [122]:
start = perf_counter()

s3_address_token_index = build_filtered_address_token_index(
    S3_PATH,
    useful_address_tokens
)

print(
    f"S3 address-token index built in "
    f"{perf_counter() - start:.2f} seconds"
)

Processed 1,000,000 rows...
Processed 2,000,000 rows...
Processed 3,000,000 rows...
Processed 4,000,000 rows...
Processed 5,000,000 rows...
Finished. Index contains 163,073 tokens.
S3 address-token index built in 313.60 seconds

In [123]:
def evaluate_address_token_block(
    s1_df,
    s2_index,
    s3_index,
    val_gt,
    max_s1=10_000
):
    total_candidates = 0
    s1_with_candidates = 0
    per_s1_counts = []

    recall_sum = 0.0
    evaluated = 0
    skipped = 0

    for i, (_, row) in enumerate(s1_df.iterrows()):

        if i >= max_s1:
            break

        s1_id = row["entity_id"]
        address = row["address_norm"]

        candidate_ids = set()

        if address:
            tokens = set(address.split())

            for token in tokens:
                candidate_ids.update(
                    s2_index.get(token, set())
                )
                candidate_ids.update(
                    s3_index.get(token, set())
                )

        n_candidates = len(candidate_ids)

        total_candidates += n_candidates
        per_s1_counts.append(n_candidates)

        if n_candidates > 0:
            s1_with_candidates += 1

        # Candidate recall
        if s1_id not in val_gt:
            skipped += 1
        else:
            true_matches = val_gt[s1_id]

            if len(true_matches) == 0:
                recall_sum += 1.0
            else:
                found = len(true_matches & candidate_ids)
                recall_sum += found / len(true_matches)

            evaluated += 1

        if (i + 1) % 2_000 == 0:
            print(
                f"Processed {i+1:,} S1 records | "
                f"candidates so far: {total_candidates:,}"
            )

    counts = np.array(per_s1_counts)

    return {
        "total_candidate_pairs": total_candidates,
        "s1_records_with_candidates": s1_with_candidates,
        "average_candidates_per_s1": counts.mean(),
        "median_candidates_per_s1": np.median(counts),
        "p95_candidates_per_s1": np.quantile(counts, 0.95),
        "p99_candidates_per_s1": np.quantile(counts, 0.99),
        "max_candidates_per_s1": counts.max(),
        "macro_candidate_recall": (
            recall_sum / evaluated
            if evaluated > 0 else 0.0
        ),
        "n_evaluated": evaluated,
        "n_skipped_no_ground_truth": skipped
    }

In [124]:
start = perf_counter()

address_token_test = evaluate_address_token_block(
    s1_val,
    s2_address_token_index,
    s3_address_token_index,
    val_gt,
    max_s1=10_000
)

print("\nADDRESS-TOKEN — 10K TEST")
print("-" * 55)

for key, value in address_token_test.items():
    print(f"{key}: {value}")

print(f"\nTime: {perf_counter() - start:.2f} seconds")

Processed 2,000 S1 records | candidates so far: 195,663,211
Processed 4,000 S1 records | candidates so far: 400,984,837
Processed 6,000 S1 records | candidates so far: 593,740,107
Processed 8,000 S1 records | candidates so far: 792,619,801
Processed 10,000 S1 records | candidates so far: 991,312,196

ADDRESS-TOKEN — 10K TEST
-------------------------------------------------------
total_candidate_pairs: 991312196
s1_records_with_candidates: 10000
average_candidates_per_s1: 99131.2196
median_candidates_per_s1: 62162.0
p95_candidates_per_s1: 284959.0999999995
p99_candidates_per_s1: 741608.5900000002
max_candidates_per_s1: 1958800
macro_candidate_recall: 0.9553388816291395
n_evaluated: 9998
n_skipped_no_ground_truth: 2

Time: 133.87 seconds

In [125]:
def evaluate_address_token_number_block(
    s1_df,
    s2_name_number_index,
    s3_name_number_index,
    s2_address_token_index,
    s3_address_token_index,
    val_gt,
    max_s1=10_000
):
    total_candidates = 0
    s1_with_candidates = 0
    per_s1_counts = []

    recall_sum = 0.0
    evaluated = 0
    skipped = 0

    for i, (_, row) in enumerate(s1_df.iterrows()):

        if i >= max_s1:
            break

        s1_id = row["entity_id"]

        # -------------------------
        # Address tokens
        # -------------------------
        address = row["address_norm"]

        token_candidates = set()

        if address:
            tokens = set(address.split())

            for token in tokens:
                token_candidates.update(
                    s2_address_token_index.get(token, set())
                )
                token_candidates.update(
                    s3_address_token_index.get(token, set())
                )

        # -------------------------
        # Address numbers
        # -------------------------
        numbers = row["address_numbers"]

        number_candidates = set()

        if numbers:
            for number in numbers:
                number_candidates.update(
                    s2_name_number_index.get(number, set())
                )
                number_candidates.update(
                    s3_name_number_index.get(number, set())
                )

        # -------------------------
        # INTERSECTION
        # -------------------------
        candidate_ids = (
            token_candidates
            & number_candidates
        )

        n_candidates = len(candidate_ids)

        total_candidates += n_candidates
        per_s1_counts.append(n_candidates)

        if n_candidates > 0:
            s1_with_candidates += 1

        # -------------------------
        # Recall
        # -------------------------
        if s1_id not in val_gt:
            skipped += 1

        else:
            true_matches = val_gt[s1_id]

            if len(true_matches) == 0:
                recall_sum += 1.0

            else:
                found = len(
                    true_matches & candidate_ids
                )

                recall_sum += (
                    found / len(true_matches)
                )

            evaluated += 1

        if (i + 1) % 2_000 == 0:
            print(
                f"Processed {i+1:,} S1 records | "
                f"candidates so far: {total_candidates:,}"
            )

    counts = np.array(per_s1_counts)

    return {
        "total_candidate_pairs": total_candidates,
        "s1_records_with_candidates": s1_with_candidates,
        "average_candidates_per_s1": counts.mean(),
        "median_candidates_per_s1": np.median(counts),
        "p95_candidates_per_s1": np.quantile(counts, 0.95),
        "p99_candidates_per_s1": np.quantile(counts, 0.99),
        "max_candidates_per_s1": counts.max(),
        "macro_candidate_recall": (
            recall_sum / evaluated
            if evaluated > 0 else 0.0
        ),
        "n_evaluated": evaluated,
        "n_skipped_no_ground_truth": skipped
    }

In [126]:
start = perf_counter()

address_token_number_test = evaluate_address_token_number_block(
    s1_val,
    s2_name_number_index,
    s3_name_number_index,
    s2_address_token_index,
    s3_address_token_index,
    val_gt,
    max_s1=10_000
)

print("\nADDRESS TOKEN + ADDRESS NUMBER — 10K TEST")
print("-" * 60)

for key, value in address_token_number_test.items():
    print(f"{key}: {value}")

print(f"\nTime: {perf_counter() - start:.2f} seconds")

Processed 2,000 S1 records | candidates so far: 0
Processed 4,000 S1 records | candidates so far: 0
Processed 6,000 S1 records | candidates so far: 0
Processed 8,000 S1 records | candidates so far: 0
Processed 10,000 S1 records | candidates so far: 0

ADDRESS TOKEN + ADDRESS NUMBER — 10K TEST
------------------------------------------------------------
total_candidate_pairs: 0
s1_records_with_candidates: 0
average_candidates_per_s1: 0.0
median_candidates_per_s1: 0.0
p95_candidates_per_s1: 0.0
p99_candidates_per_s1: 0.0
max_candidates_per_s1: 0
macro_candidate_recall: 0.05731146229245849
n_evaluated: 9998
n_skipped_no_ground_truth: 2

Time: 128.73 seconds

In [127]:
from collections import defaultdict
from time import perf_counter

def build_address_number_index(
    path,
    number_frequency,
    max_number_frequency=5000,
    chunk_size=200_000
):
    index = defaultdict(set)
    total_rows = 0

    allowed_numbers = {
        number
        for number, count in number_frequency.items()
        if count <= max_number_frequency
    }

    print("Allowed address numbers:", len(allowed_numbers))

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=["entity_id", "business_address"],
        chunksize=chunk_size
    ):
        total_rows += len(chunk)

        chunk["address_norm"] = (
            chunk["business_address"]
            .fillna("")
            .map(normalize_text)
        )

        for _, row in chunk.iterrows():

            address = row["address_norm"]

            if not address:
                continue

            numbers = set(
                re.findall(r"\d+", address)
            )

            numbers &= allowed_numbers

            for number in numbers:
                index[number].add(row["entity_id"])

        if total_rows % 1_000_000 < chunk_size:
            print(f"Processed {total_rows:,} rows...")

    print(
        f"Finished. Index contains "
        f"{len(index):,} address numbers."
    )

    return index

In [128]:
start = perf_counter()

s2_address_number_index = build_address_number_index(
    S2_PATH,
    s2_address_number_frequency,
    max_number_frequency=5000
)

print(
    f"S2 address-number index built in "
    f"{perf_counter() - start:.2f} seconds"
)

Allowed address numbers: 96796
Processed 1,000,000 rows...
Processed 2,000,000 rows...
Processed 3,000,000 rows...
Processed 4,000,000 rows...
Processed 5,000,000 rows...
Processed 5,034,616 rows...
Finished. Index contains 71,945 address numbers.
S2 address-number index built in 226.32 seconds

In [129]:
start = perf_counter()

s3_address_number_index = build_address_number_index(
    S3_PATH,
    s3_address_number_frequency,
    max_number_frequency=5000
)

print(
    f"S3 address-number index built in "
    f"{perf_counter() - start:.2f} seconds"
)

Allowed address numbers: 97470
Processed 1,000,000 rows...
Processed 2,000,000 rows...
Processed 3,000,000 rows...
Processed 4,000,000 rows...
Processed 5,000,000 rows...
Finished. Index contains 72,281 address numbers.
S3 address-number index built in 229.80 seconds

In [130]:
def evaluate_address_number_block(
    s1_df,
    s2_index,
    s3_index,
    val_gt,
    max_s1=None
):
    total_candidates = 0
    s1_records_with_candidates = 0
    per_s1_counts = []

    recall_sum = 0.0
    evaluated = 0
    skipped = 0

    for i, (_, row) in enumerate(s1_df.iterrows()):

        if max_s1 is not None and i >= max_s1:
            break

        s1_id = row["entity_id"]
        numbers = row["address_numbers"]

        candidate_ids = set()

        for number in numbers:
            candidate_ids.update(s2_index.get(number, set()))
            candidate_ids.update(s3_index.get(number, set()))

        n_candidates = len(candidate_ids)

        total_candidates += n_candidates

        if n_candidates > 0:
            s1_records_with_candidates += 1

        per_s1_counts.append(n_candidates)

        if s1_id not in val_gt:
            skipped += 1
        else:
            true_matches = val_gt[s1_id]

            if len(true_matches) == 0:
                recall_sum += 1.0
            else:
                found = len(true_matches & candidate_ids)
                recall_sum += found / len(true_matches)

            evaluated += 1

        if (i + 1) % 2000 == 0:
            print(
                f"Processed {i + 1:,} S1 records | "
                f"candidates so far: {total_candidates:,}"
            )

    import numpy as np

    counts = np.array(per_s1_counts)

    return {
        "total_candidate_pairs": total_candidates,
        "s1_records_with_candidates": s1_records_with_candidates,
        "average_candidates_per_s1": counts.mean(),
        "median_candidates_per_s1": np.median(counts),
        "p95_candidates_per_s1": np.quantile(counts, 0.95),
        "p99_candidates_per_s1": np.quantile(counts, 0.99),
        "max_candidates_per_s1": counts.max(),
        "macro_candidate_recall": (
            recall_sum / evaluated
            if evaluated > 0 else 0.0
        ),
        "n_evaluated": evaluated,
        "n_skipped_no_ground_truth": skipped
    }

In [131]:
start = perf_counter()

address_number_test = evaluate_address_number_block(
    s1_val,
    s2_address_number_index,
    s3_address_number_index,
    val_gt,
    max_s1=10_000
)

print("\nADDRESS NUMBER — 10K TEST")
print("-" * 60)

for key, value in address_number_test.items():
    print(f"{key}: {value}")

print(f"\nTime: {perf_counter() - start:.2f} seconds")

Processed 2,000 S1 records | candidates so far: 3,530,203
Processed 4,000 S1 records | candidates so far: 6,799,078
Processed 6,000 S1 records | candidates so far: 9,955,869
Processed 8,000 S1 records | candidates so far: 13,113,241
Processed 10,000 S1 records | candidates so far: 16,668,036

ADDRESS NUMBER — 10K TEST
------------------------------------------------------------
total_candidate_pairs: 16668036
s1_records_with_candidates: 6069
average_candidates_per_s1: 1666.8036
median_candidates_per_s1: 201.5
p95_candidates_per_s1: 8259.449999999993
p99_candidates_per_s1: 10392.02
max_candidates_per_s1: 26427
macro_candidate_recall: 0.49492818837938063
n_evaluated: 9998
n_skipped_no_ground_truth: 2

Time: 4.33 seconds

In [147]:
def generate_combined_candidates(
    row,
    s2_name_index,
    s3_name_index,
    s2_name_token_index,
    s3_name_token_index,
    s2_address_number_index,
    s3_address_number_index,
    s2_name_number_index,
    s3_name_number_index,
    s2_token_frequency,
    s3_token_frequency,
    s2_address_number_frequency,
    s3_address_number_frequency,
    max_name_frequency=5000,
    max_number_frequency=5000
):

    candidate_ids = set()

    name = normalize_text(row["business_name"])

    numbers = extract_address_numbers(
        row["business_address"]
    )

    # =========================================
    # 1. EXACT NORMALIZED NAME
    # =========================================

    if name:

        candidate_ids.update(
            s2_name_index.get(name, set())
        )

        candidate_ids.update(
            s3_name_index.get(name, set())
        )
    if name:

        candidate_ids.update(
            s2_full_name_index.get(name, set())
        )

        candidate_ids.update(
            s3_full_name_index.get(name, set())
        )

    # =========================================
    # 2. RARE NAME TOKEN
    # =========================================

    tokens = set(name.split()) if name else set()

    usable_tokens = [
        token
        for token in tokens
        if (
            s2_token_frequency.get(
                token,
                float("inf")
            ) <= max_name_frequency
            or
            s3_token_frequency.get(
                token,
                float("inf")
            ) <= max_name_frequency
        )
    ]

    for token in usable_tokens:

        candidate_ids.update(
            s2_name_token_index.get(token, set())
        )

        candidate_ids.update(
            s3_name_token_index.get(token, set())
        )

    # =========================================
    # 3. ADDRESS NUMBER
    # =========================================

    usable_numbers = [
        number
        for number in numbers
        if (
            s2_address_number_frequency.get(
                number,
                float("inf")
            ) <= max_number_frequency
            or
            s3_address_number_frequency.get(
                number,
                float("inf")
            ) <= max_number_frequency
        )
    ]

    for number in usable_numbers:

        candidate_ids.update(
            s2_address_number_index.get(
                number,
                set()
            )
        )

        candidate_ids.update(
            s3_address_number_index.get(
                number,
                set()
            )
        )

    # =========================================
    # 4. NAME TOKEN + ADDRESS NUMBER
    # =========================================

    for token in usable_tokens:

        for number in usable_numbers:

            key = (token, number)

            candidate_ids.update(
                s2_name_number_index.get(
                    key,
                    set()
                )
            )

            candidate_ids.update(
                s3_name_number_index.get(
                    key,
                    set()
                )
            )

    return candidate_ids

In [148]:
[name for name in globals() if "frequency" in name.lower()]

['token_frequency_s2',
 'token_frequency_s3',
 'token_frequency_full',
 's2_token_frequency',
 's3_token_frequency',
 'build_address_number_frequency',
 's2_address_number_frequency',
 's3_address_number_frequency',
 'build_address_token_frequency',
 's1_address_frequency']

In [149]:
from time import perf_counter
import numpy as np

start = perf_counter()

combined_counts = []
combined_recall_sum = 0.0
combined_evaluated = 0
combined_skipped = 0

for i, (_, row) in enumerate(s1_val.iterrows()):

    if i >= 10_000:
        break

    s1_id = row["entity_id"]

    # Generate UNION of all blocking methods
    candidate_ids = generate_combined_candidates(
        row,

        s2_name_index,
        s3_name_index,

        s2_name_token_index,
        s3_name_token_index,

        s2_address_number_index,
        s3_address_number_index,

        s2_name_number_index,
        s3_name_number_index,

        s2_token_frequency,
        s3_token_frequency,
        s2_address_number_frequency,
        s3_address_number_frequency,

        max_name_frequency=5000,
        max_number_frequency=5000
    )

    # -----------------------------------------
    # Candidate count
    # -----------------------------------------

    n_candidates = len(candidate_ids)

    combined_counts.append(n_candidates)

    # -----------------------------------------
    # Candidate recall
    # -----------------------------------------

    if s1_id not in val_gt:

        combined_skipped += 1

    else:

        true_matches = val_gt[s1_id]

        if len(true_matches) == 0:

            combined_recall_sum += 1.0

        else:

            found = len(
                true_matches & candidate_ids
            )

            combined_recall_sum += (
                found / len(true_matches)
            )

        combined_evaluated += 1

    # -----------------------------------------
    # Progress
    # -----------------------------------------

    if (i + 1) % 2_000 == 0:

        print(
            f"Processed {i + 1:,} S1 records | "
            f"candidates so far: "
            f"{sum(combined_counts):,}"
        )


# =========================================
# RESULTS
# =========================================

counts = np.array(combined_counts)

print("\nCOMBINED BLOCKER — 10K TEST")
print("-" * 60)

print(
    "total_candidate_pairs:",
    counts.sum()
)

print(
    "s1_records_with_candidates:",
    np.sum(counts > 0)
)

print(
    "average_candidates_per_s1:",
    counts.mean()
)

print(
    "median_candidates_per_s1:",
    np.median(counts)
)

print(
    "p95_candidates_per_s1:",
    np.quantile(counts, 0.95)
)

print(
    "p99_candidates_per_s1:",
    np.quantile(counts, 0.99)
)

print(
    "max_candidates_per_s1:",
    counts.max()
)

print(
    "macro_candidate_recall:",
    (
        combined_recall_sum / combined_evaluated
        if combined_evaluated
        else 0.0
    )
)

print(
    "n_evaluated:",
    combined_evaluated
)

print(
    "n_skipped_no_ground_truth:",
    combined_skipped
)

print(
    f"\nTime: {perf_counter() - start:.2f} seconds"
)

Processed 2,000 S1 records | candidates so far: 3,551,186
Processed 4,000 S1 records | candidates so far: 6,839,550
Processed 6,000 S1 records | candidates so far: 10,013,618
Processed 8,000 S1 records | candidates so far: 13,189,672
Processed 10,000 S1 records | candidates so far: 16,766,142

COMBINED BLOCKER — 10K TEST
------------------------------------------------------------
total_candidate_pairs: 16766142
s1_records_with_candidates: 9211
average_candidates_per_s1: 1676.6142
median_candidates_per_s1: 216.5
p95_candidates_per_s1: 8318.0
p99_candidates_per_s1: 10392.050000000001
max_candidates_per_s1: 26438
macro_candidate_recall: 0.6090772519583284
n_evaluated: 9998
n_skipped_no_ground_truth: 2

Time: 5.83 seconds

In [150]:
from collections import defaultdict

block_counts = defaultdict(int)

for i, (_, row) in enumerate(s1_val.iterrows()):

    if i >= 10_000:
        break

    name = normalize_text(row["business_name"])
    numbers = extract_address_numbers(
        row["business_address"]
    )

    # -----------------------------
    # Exact name
    # -----------------------------

    exact_name = set()

    if name:
        exact_name.update(
            s2_name_index.get(name, set())
        )
        exact_name.update(
            s3_name_index.get(name, set())
        )

    # -----------------------------
    # Rare name token
    # -----------------------------

    name_token = set()

    tokens = set(name.split()) if name else set()

    usable_tokens = [
        token
        for token in tokens
        if (
            s2_token_frequency.get(
                token,
                float("inf")
            ) <= 5000
            or
            s3_token_frequency.get(
                token,
                float("inf")
            ) <= 5000
        )
    ]

    for token in usable_tokens:
        name_token.update(
            s2_name_token_index.get(token, set())
        )
        name_token.update(
            s3_name_token_index.get(token, set())
        )

    # -----------------------------
    # Address number
    # -----------------------------

    address_number = set()

    usable_numbers = [
        number
        for number in numbers
        if (
            s2_address_number_frequency.get(
                number,
                float("inf")
            ) <= 5000
            or
            s3_address_number_frequency.get(
                number,
                float("inf")
            ) <= 5000
        )
    ]

    for number in usable_numbers:
        address_number.update(
            s2_address_number_index.get(
                number,
                set()
            )
        )
        address_number.update(
            s3_address_number_index.get(
                number,
                set()
            )
        )

    # -----------------------------
    # Name + number
    # -----------------------------

    name_number = set()

    for token in usable_tokens:
        for number in usable_numbers:

            key = (token, number)

            name_number.update(
                s2_name_number_index.get(
                    key,
                    set()
                )
            )

            name_number.update(
                s3_name_number_index.get(
                    key,
                    set()
                )
            )

    # -----------------------------
    # Track unique contribution
    # -----------------------------

    all_candidates = (
        exact_name
        | name_token
        | address_number
        | name_number
    )

    block_counts["exact_name"] += len(exact_name)
    block_counts["name_token"] += len(name_token)
    block_counts["address_number"] += len(address_number)
    block_counts["name_number"] += len(name_number)
    block_counts["combined_unique"] += len(all_candidates)

print("AVERAGE CANDIDATES PER S1")
print("-" * 50)

for key, value in block_counts.items():
    print(
        f"{key}: "
        f"{value / 10_000:.2f}"
    )

AVERAGE CANDIDATES PER S1
--------------------------------------------------
exact_name: 0.00
name_token: 0.66
address_number: 1666.80
name_number: 1.58
combined_unique: 1667.53

In [151]:
# =========================================
# RECALL CONTRIBUTION OF EACH BLOCK
# 10K VALIDATION
# =========================================

block_recall = {
    "exact_name": 0.0,
    "name_token": 0.0,
    "address_number": 0.0,
    "name_number": 0.0,
    "combined": 0.0
}

evaluated = 0
skipped = 0

for i, (_, row) in enumerate(s1_val.iterrows()):

    if i >= 10_000:
        break

    s1_id = row["entity_id"]

    if s1_id not in val_gt:
        skipped += 1
        continue

    true_matches = val_gt[s1_id]

    if len(true_matches) == 0:
        continue

    name = normalize_text(row["business_name"])

    numbers = extract_address_numbers(
        row["business_address"]
    )

    # =====================================
    # EXACT NAME
    # =====================================

    exact_name = set()

    if name:
        exact_name.update(
            s2_name_index.get(name, set())
        )
        exact_name.update(
            s3_name_index.get(name, set())
        )

    # =====================================
    # NAME TOKEN
    # =====================================

    name_token = set()

    tokens = set(name.split()) if name else set()

    usable_tokens = [
        token
        for token in tokens
        if (
            s2_token_frequency.get(
                token,
                float("inf")
            ) <= 5000
            or
            s3_token_frequency.get(
                token,
                float("inf")
            ) <= 5000
        )
    ]

    for token in usable_tokens:

        name_token.update(
            s2_name_token_index.get(
                token,
                set()
            )
        )

        name_token.update(
            s3_name_token_index.get(
                token,
                set()
            )
        )

    # =====================================
    # ADDRESS NUMBER
    # =====================================

    address_number = set()

    usable_numbers = [
        number
        for number in numbers
        if (
            s2_address_number_frequency.get(
                number,
                float("inf")
            ) <= 5000
            or
            s3_address_number_frequency.get(
                number,
                float("inf")
            ) <= 5000
        )
    ]

    for number in usable_numbers:

        address_number.update(
            s2_address_number_index.get(
                number,
                set()
            )
        )

        address_number.update(
            s3_address_number_index.get(
                number,
                set()
            )
        )

    # =====================================
    # NAME + NUMBER
    # =====================================

    name_number = set()

    for token in usable_tokens:

        for number in usable_numbers:

            key = (token, number)

            name_number.update(
                s2_name_number_index.get(
                    key,
                    set()
                )
            )

            name_number.update(
                s3_name_number_index.get(
                    key,
                    set()
                )
            )

    # =====================================
    # COMBINED UNION
    # =====================================

    combined = (
        exact_name
        | name_token
        | address_number
        | name_number
    )

    # =====================================
    # RECALL
    # =====================================

    block_recall["exact_name"] += (
        len(true_matches & exact_name)
        / len(true_matches)
    )

    block_recall["name_token"] += (
        len(true_matches & name_token)
        / len(true_matches)
    )

    block_recall["address_number"] += (
        len(true_matches & address_number)
        / len(true_matches)
    )

    block_recall["name_number"] += (
        len(true_matches & name_number)
        / len(true_matches)
    )

    block_recall["combined"] += (
        len(true_matches & combined)
        / len(true_matches)
    )

    evaluated += 1


print("\nRECALL CONTRIBUTION — 10K TEST")
print("-" * 60)

for block, value in block_recall.items():

    print(
        f"{block}: "
        f"{value / evaluated:.6f}"
    )

print("\nEvaluated:", evaluated)
print("Skipped:", skipped)

RECALL CONTRIBUTION — 10K TEST
------------------------------------------------------------
exact_name: 0.000000
name_token: 0.000141
address_number: 0.464222
name_number: 0.310250
combined: 0.475366

Evaluated: 9425
Skipped: 2

In [152]:
[name for name in globals()
 if "name" in name.lower()
 and "index" in name.lower()]

['build_name_index',
 's2_name_index',
 's3_name_index',
 's2_name_token_index',
 's3_name_token_index',
 'build_full_name_index',
 's2_full_name_index',
 's3_full_name_index',
 'build_name_number_index',
 's2_name_number_index',
 's3_name_number_index']

In [153]:
# Compare the two name indexes on the same 10K validation records

exact_name_recall = {
    "name_index": 0.0,
    "full_name_index": 0.0
}

evaluated = 0

for i, (_, row) in enumerate(s1_val.iterrows()):

    if i >= 10_000:
        break

    s1_id = row["entity_id"]

    if s1_id not in val_gt:
        continue

    true_matches = val_gt[s1_id]

    if len(true_matches) == 0:
        continue

    name = normalize_text(row["business_name"])

    # -----------------------------------------
    # s2_name_index / s3_name_index
    # -----------------------------------------

    candidates_name = set()

    if name:
        candidates_name.update(
            s2_name_index.get(name, set())
        )
        candidates_name.update(
            s3_name_index.get(name, set())
        )

    # -----------------------------------------
    # s2_full_name_index / s3_full_name_index
    # -----------------------------------------

    candidates_full_name = set()

    if name:
        candidates_full_name.update(
            s2_full_name_index.get(name, set())
        )
        candidates_full_name.update(
            s3_full_name_index.get(name, set())
        )

    # -----------------------------------------
    # Recall
    # -----------------------------------------

    exact_name_recall["name_index"] += (
        len(true_matches & candidates_name)
        / len(true_matches)
    )

    exact_name_recall["full_name_index"] += (
        len(true_matches & candidates_full_name)
        / len(true_matches)
    )

    evaluated += 1


print("EXACT NAME INDEX COMPARISON")
print("-" * 50)

for key, value in exact_name_recall.items():

    print(
        f"{key}: "
        f"{value / evaluated:.6f}"
    )

print("\nEvaluated:", evaluated)

EXACT NAME INDEX COMPARISON
--------------------------------------------------
name_index: 0.000000
full_name_index: 0.221225

Evaluated: 9425